version: '3.7'


services:
  db:
    environment:
      POSTGRES_MULTIPLE_DATABASES: mikro_db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: fostgres
    image: jhnnsrs/daten:next
    labels:
      - "arkitekt.default.service=db"
  mikro:
    build: .
    ports:
    - 8888:80
    labels:
      - "arkitekt.default.service=mikro"
      - "traefik.enable=true"
      - "traefik.http.routers.mikro.entrypoints=mikrosecure"
      - "traefik.http.routers.mikro.rule=Host(`jhnnsrs-server.hyena-sole.ts.net`)"
      - "traefik.http.services.mikro.loadbalancer.server.port=8080"
      - "traefik.http.routers.mikro.tls.certresolver=myresolver"
  minio:
    command: server /data  --console-address ":9001"
    environment:
      MINIO_ROOT_PASSWORD: e8821a29d189789e39c9922a3bfcfb4a
      MINIO_ROOT_USER: crappygreysetter
    image: minio/minio:RELEASE.2023-02-10T18-48-39Z
    ports:
      - 9002:9000
    volumes:
    - ./data:/data
    labels:
      - "arkitekt.default.service=s3"
  redis:
    image: redis:latest
    labels:
      - "arkitekt.default.service=redis"

