# Generated by Django 4.2.8 on 2024-08-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolstepmapping",
            name="t",
            field=models.IntegerField(
                blank=True,
                help_text="The relative time of the step according to the lifetime of each sample?",
                null=True,
            ),
        ),
    ]
