# Generated by Django 4.2.3 on 2023-08-01 13:57

from django.conf import settings
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="pinned_by",
            field=models.ManyToManyField(
                help_text="The users that have pinned the images",
                related_name="pinned_images",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
