# Generated by Django 4.2.8 on 2024-09-02 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expression",
            name="store",
            field=models.ForeignKey(
                blank=True,
                help_text="The store of the image class",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.mediastore",
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="ontology",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expressions",
                to="core.ontology",
            ),
        ),
    ]
