# Generated by Django 6.0.6 on 2026-08-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallayer",
            name="point_color_bys",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="(point) The colourings this layer offers, in the order a picker should show them. Each colours points by a column of a table this layer's ids key into, or by one slice of a sparse matrix they index. Empty means every point takes the flat colour",
            ),
        ),
        migrations.AddField(
            model_name="historicallayer",
            name="point_filter_bys",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="(point) The filters this layer offers, in the order a picker should show them. Each keeps or drops points by a column of a table this layer's ids key into. Empty means nothing is offered and every point draws",
            ),
        ),
        migrations.AddField(
            model_name="layer",
            name="point_color_bys",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="(point) The colourings this layer offers, in the order a picker should show them. Each colours points by a column of a table this layer's ids key into, or by one slice of a sparse matrix they index. Empty means every point takes the flat colour",
            ),
        ),
        migrations.AddField(
            model_name="layer",
            name="point_filter_bys",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="(point) The filters this layer offers, in the order a picker should show them. Each keeps or drops points by a column of a table this layer's ids key into. Empty means nothing is offered and every point draws",
            ),
        ),
    ]
