# Generated by Django 5.2 on 2025-07-29 12:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelview',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='historicalchannelview',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='historicalchannel',
            name='history_relation',
        ),
        migrations.RemoveField(
            model_name='historicalchannel',
            name='client',
        ),
        migrations.RemoveField(
            model_name='historicalchannel',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpixelview',
            name='client',
        ),
        migrations.RemoveField(
            model_name='historicalpixelview',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='historicalpixelview',
            name='history_relation',
        ),
        migrations.RemoveField(
            model_name='historicalpixelview',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpixelview',
            name='image',
        ),
        migrations.RemoveField(
            model_name='historicalstructureview',
            name='client',
        ),
        migrations.RemoveField(
            model_name='historicalstructureview',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='historicalstructureview',
            name='history_relation',
        ),
        migrations.RemoveField(
            model_name='historicalstructureview',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalstructureview',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pixellabel',
            name='pinned_by',
        ),
        migrations.RemoveField(
            model_name='pixellabel',
            name='view',
        ),
        migrations.RemoveField(
            model_name='pixelview',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='pixelview',
            name='image',
        ),
        migrations.RemoveField(
            model_name='labelaccessor',
            name='pixel_view',
        ),
        migrations.RemoveField(
            model_name='structureview',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='structureview',
            name='image',
        ),
        migrations.RemoveField(
            model_name='acquisitionview',
            name='entity_id',
        ),
        migrations.RemoveField(
            model_name='historicalrgbview',
            name='active',
        ),
        migrations.RemoveField(
            model_name='historicalrgbview',
            name='rescale',
        ),
        migrations.RemoveField(
            model_name='historicalroi',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='rgbview',
            name='active',
        ),
        migrations.RemoveField(
            model_name='rgbview',
            name='rescale',
        ),
        migrations.RemoveField(
            model_name='roi',
            name='entity',
        ),
        migrations.AddField(
            model_name='channelview',
            name='acquisition_mode',
            field=models.CharField(blank=True, help_text='The acquisition mode of the channel', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='channelview',
            name='emission_wavelength',
            field=models.FloatField(blank=True, help_text='The emmission wavelength of the fluorophore in nm', null=True),
        ),
        migrations.AddField(
            model_name='channelview',
            name='excitation_wavelength',
            field=models.FloatField(blank=True, help_text='The excitation wavelength of the fluorophore in nm', null=True),
        ),
        migrations.AddField(
            model_name='channelview',
            name='name',
            field=models.CharField(blank=True, help_text='The name of the channel', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historicalchannelview',
            name='acquisition_mode',
            field=models.CharField(blank=True, help_text='The acquisition mode of the channel', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historicalchannelview',
            name='emission_wavelength',
            field=models.FloatField(blank=True, help_text='The emmission wavelength of the fluorophore in nm', null=True),
        ),
        migrations.AddField(
            model_name='historicalchannelview',
            name='excitation_wavelength',
            field=models.FloatField(blank=True, help_text='The excitation wavelength of the fluorophore in nm', null=True),
        ),
        migrations.AddField(
            model_name='historicalchannelview',
            name='name',
            field=models.CharField(blank=True, help_text='The name of the channel', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalroi',
            name='image',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The Image this ROI was original used to create (drawn on)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.image'),
        ),
        migrations.AlterField(
            model_name='roi',
            name='image',
            field=models.ForeignKey(default=1, help_text='The Image this ROI was original used to create (drawn on)', on_delete=django.db.models.deletion.CASCADE, related_name='rois', to='core.image'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CropView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('z_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('x_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('x_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('y_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('y_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('t_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('t_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('c_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('c_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('is_global', models.BooleanField(default=False, help_text='Whether the view is global or not')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.viewcollection')),
                ('image', simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.image')),
                ('roi', models.ForeignKey(help_text='The ROI that defines the crop', on_delete=django.db.models.deletion.CASCADE, related_name='crop_views', to='core.roi')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaskView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('z_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('x_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('x_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('y_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('y_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('t_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('t_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('c_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('c_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('is_global', models.BooleanField(default=False, help_text='Whether the view is global or not')),
                ('labels', models.JSONField(default=list, help_text='The labels of the mask, and their corresponding colors')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.viewcollection')),
                ('image', simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.image')),
            ],
            options={
                'default_related_name': 'mask_views',
            },
        ),
        migrations.AddField(
            model_name='labelaccessor',
            name='mask_view',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='label_accessors', to='core.maskview'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReferenceView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('z_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('x_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('x_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('y_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('y_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('t_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('t_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('c_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('c_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('is_global', models.BooleanField(default=False, help_text='Whether the view is global or not')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.viewcollection')),
                ('image', simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.image')),
            ],
            options={
                'default_related_name': 'reference_views',
            },
        ),
        migrations.AddField(
            model_name='maskview',
            name='reference_view',
            field=models.ForeignKey(help_text='The view that is masked by this mask', on_delete=django.db.models.deletion.CASCADE, related_name='mask_views', to='core.referenceview'),
        ),
        migrations.CreateModel(
            name='InstanceMaskView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('z_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('x_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('x_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('y_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('y_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('t_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('t_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('c_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('c_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('is_global', models.BooleanField(default=False, help_text='Whether the view is global or not')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.viewcollection')),
                ('image', simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.image')),
                ('reference_view', models.ForeignKey(help_text='The view that is masked by this mask', on_delete=django.db.models.deletion.CASCADE, related_name='instance_mask_views', to='core.referenceview')),
            ],
            options={
                'default_related_name': 'instance_mask_views',
            },
        ),
        migrations.CreateModel(
            name='HistoricalReferenceView',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('assignation_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('z_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('z_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('x_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('x_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('y_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('y_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('t_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('t_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('c_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('c_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('is_global', models.BooleanField(default=False, help_text='Whether the view is global or not')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client')),
                ('collection', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.viewcollection')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('image', simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.image')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.referenceview')),
            ],
            options={
                'verbose_name': 'historical reference view',
                'verbose_name_plural': 'historical reference views',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInstanceMaskView',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('assignation_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('z_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('z_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('x_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('x_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('y_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('y_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('t_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('t_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('c_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('c_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('is_global', models.BooleanField(default=False, help_text='Whether the view is global or not')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client')),
                ('collection', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.viewcollection')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('image', simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.image')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.instancemaskview')),
                ('reference_view', models.ForeignKey(blank=True, db_constraint=False, help_text='The view that is masked by this mask', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.referenceview')),
            ],
            options={
                'verbose_name': 'historical instance mask view',
                'verbose_name_plural': 'historical instance mask views',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='HistoricalChannel',
        ),
        migrations.DeleteModel(
            name='HistoricalPixelView',
        ),
        migrations.DeleteModel(
            name='HistoricalStructureView',
        ),
        migrations.DeleteModel(
            name='PixelLabel',
        ),
        migrations.DeleteModel(
            name='PixelView',
        ),
        migrations.DeleteModel(
            name='StructureView',
        ),
    ]
