# Generated by Django 5.2 on 2026-04-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='content_type',
            field=models.CharField(blank=True, help_text='The content type of the file', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(blank=True, help_text='The size of the file in bytes', null=True),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='content_type',
            field=models.CharField(blank=True, help_text='The content type of the file', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='size',
            field=models.BigIntegerField(blank=True, help_text='The size of the file in bytes', null=True),
        ),
    ]
