# Generated by Django 5.2 on 2026-03-31 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='lens',
            field=models.ForeignKey(help_text='The lens that defines the data source and constraints of the placement', on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='core.lens'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='core.scene'),
        ),
        migrations.CreateModel(
            name='ValueHistogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('histogram', models.JSONField(default=list, help_text='The histogram of the pixel values (y values)')),
                ('bins', models.JSONField(default=list, help_text='The bin indices of the histogram (x values)')),
                ('min', models.FloatField(blank=True, help_text='The minimum pixel value of the histogram', null=True)),
                ('max', models.FloatField(blank=True, help_text='The maximum pixel value of the histogram', null=True)),
                ('p1', models.FloatField(blank=True, help_text='The first percentile of the pixel values', null=True)),
                ('p99', models.FloatField(blank=True, help_text='The 99th percentile of the pixel values', null=True)),
                ('anchor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_histogram', to='core.coordinateanchor')),
            ],
        ),
    ]
