# Generated by Django 4.2.8 on 2024-07-29 11:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_entity_entitykind_historicalentity_ontology_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entity",
            old_name="of",
            new_name="parent",
        ),
        migrations.RenameField(
            model_name="historicalentity",
            old_name="of",
            new_name="parent",
        ),
    ]
