# Generated by Django 6.0.6 on 2026-08-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallayer',
            name='mesh_color_by',
            field=models.JSONField(blank=True, default=None, help_text="(mesh) Color objects by a column of the table this collection's FIELD edge keys into, instead of by the flat material color. Null renders the material color", null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='mesh_color_by',
            field=models.JSONField(blank=True, default=None, help_text="(mesh) Color objects by a column of the table this collection's FIELD edge keys into, instead of by the flat material color. Null renders the material color", null=True),
        ),
    ]
