# Generated by Django 5.2 on 2025-11-29 11:26

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0002_membership'),
        ('core', '0002_file_membership_historicalfile_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the meta schema', max_length=1000)),
                ('schema', models.JSONField(help_text='The schema definition in JSON Schema format')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalMetaSchema',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('assignation_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(help_text='The name of the meta schema', max_length=1000)),
                ('schema', models.JSONField(help_text='The schema definition in JSON Schema format')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.metaschema')),
            ],
            options={
                'verbose_name': 'historical meta schema',
                'verbose_name_plural': 'historical meta schemas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='UnstructuredMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the meta data', max_length=1000)),
                ('meta', models.JSONField(help_text='The unstructured meta data of the file')),
                ('file', simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unstructured_metas', to='core.file')),
                ('schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.metaschema')),
            ],
        ),
    ]
