"""A mesh layer publishes a picker of *filters* as well as one of colourings.

Purely additive, and deliberately not folded into 0002: nothing moves, and every column
arrives with a default that is the honest reading of a row written before it existed -- an
empty picker offers nothing, an empty active set applies nothing, and every object draws,
which is what every existing mesh layer already does.

`active_filter_bys` is a JSON list rather than an integer column because filters compose:
several are applied at once and ANDed, where a layer draws exactly one colouring.
"""

# Generated by Django 6.0.6 on 2026-08-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mesh_color_picker'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallayer',
            name='active_filter_bys',
            field=models.JSONField(blank=True, default=list, help_text='(mesh) Which entries of `meshFilterBys` are currently applied, as indices into it. Combined with AND -- an object is drawn when every active rule keeps it. Empty applies none of them, so everything draws'),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='mesh_filter_bys',
            field=models.JSONField(blank=True, default=list, help_text="(mesh) The filters this layer offers, in the order a picker should show them. Each keeps or drops objects by a column of a table this collection's FIELD edge keys into. Empty means nothing is offered and every object draws"),
        ),
        migrations.AddField(
            model_name='layer',
            name='active_filter_bys',
            field=models.JSONField(blank=True, default=list, help_text='(mesh) Which entries of `meshFilterBys` are currently applied, as indices into it. Combined with AND -- an object is drawn when every active rule keeps it. Empty applies none of them, so everything draws'),
        ),
        migrations.AddField(
            model_name='layer',
            name='mesh_filter_bys',
            field=models.JSONField(blank=True, default=list, help_text="(mesh) The filters this layer offers, in the order a picker should show them. Each keeps or drops objects by a column of a table this collection's FIELD edge keys into. Empty means nothing is offered and every object draws"),
        ),
    ]
