# Generated by Django 5.2 on 2026-03-31 13:59

import core.enums
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_layer_lens_alter_layer_scene_valuehistogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroi',
            name='kind',
            field=django_choices_field.fields.TextChoicesField(choices=[('ellipse', 'Ellipse'), ('polygon', 'POLYGON'), ('line', 'Line'), ('rectangle', 'Rectangle (XY)'), ('spectral_rectangle', 'Spectral Rectangle (XYC)'), ('temporal_rectangle', 'Temporal Rectangle (XYT)'), ('cube', 'Cube (XYZ)'), ('spectral_cube', 'Spectral Cube (XYZC)'), ('temporal_cube', 'Temporal Cube (XYZT)'), ('hypercube', 'Hypercube (XYZT)'), ('spectral_hypercube', 'Spectral Hypercube (XYZTC)'), ('path', 'Path'), ('unknown', 'Unknown'), ('frame', 'Frame'), ('slice', 'Slice'), ('point', 'Point')], choices_enum=core.enums.RoiKindChoices, default='path', help_text='The Roi can have vasrying kind, consult your API', max_length=18),
        ),
        migrations.AddField(
            model_name='dataroi',
            name='x_dim',
            field=models.CharField(default=1, help_text='The name of the x dimension in the data source', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataroi',
            name='x_max',
            field=models.IntegerField(blank=True, help_text='The maximum x coordinate of the ROI', null=True),
        ),
        migrations.AddField(
            model_name='dataroi',
            name='x_min',
            field=models.IntegerField(blank=True, help_text='The minimum x coordinate of the ROI', null=True),
        ),
        migrations.AddField(
            model_name='dataroi',
            name='y_dim',
            field=models.CharField(default=1, help_text='The name of the y dimension in the data source', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataroi',
            name='y_max',
            field=models.IntegerField(blank=True, help_text='The maximum y coordinate of the ROI', null=True),
        ),
        migrations.AddField(
            model_name='dataroi',
            name='y_min',
            field=models.IntegerField(blank=True, help_text='The minimum y coordinate of the ROI', null=True),
        ),
        migrations.AddField(
            model_name='dataroi',
            name='z_dim',
            field=models.CharField(blank=True, help_text='The name of the z dimension in the data source', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dataroi',
            name='z_max',
            field=models.IntegerField(blank=True, help_text='The maximum z coordinate of the ROI', null=True),
        ),
        migrations.AddField(
            model_name='dataroi',
            name='z_min',
            field=models.IntegerField(blank=True, help_text='The minimum z coordinate of the ROI', null=True),
        ),
    ]
