# Generated by Django 6.0.6 on 2026-07-06 11:11

import core.enums
import core.models.view
import django.db.models.deletion
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallayer',
            name='color_by_column',
            field=models.CharField(blank=True, help_text='(track) The table column used to color tracks (used with colormap)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='color_column',
            field=models.CharField(blank=True, help_text='(point) The table column mapped to per-point color/intensity (used with colormap)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='data_roi',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='(shape) The data ROI whose vectors this layer renders', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.dataroi'),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='fill_color',
            field=models.JSONField(blank=True, default=None, help_text='(shape) The fill color of the geometry (RGBA), or null for no fill', null=True),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='filled',
            field=models.BooleanField(default=False, help_text='(shape) Whether the geometry is filled with fill_color'),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='id_column',
            field=models.CharField(blank=True, help_text='(point) The table column identifying each point', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='kind',
            field=django_choices_field.fields.TextChoicesField(choices=[('image', 'Image (array data)'), ('shape', 'Shape (ROI geometry)'), ('point', 'Point (tabular point cloud)'), ('track', 'Track (tabular trajectories)'), ('mesh', 'Mesh (3D surface)')], choices_enum=core.enums.LayerKindChoices, default='image', help_text='The kind of layer, discriminating its data source and render settings', max_length=5),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='line_width',
            field=models.FloatField(blank=True, help_text='(track) The width of the track lines, in scene units', null=True),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='material_color',
            field=models.JSONField(blank=True, default=None, help_text='(mesh) The material (surface) color of the mesh (RGBA)', null=True),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='mesh',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='(mesh) The mesh whose geometry this layer renders', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.mesh'),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='opacity',
            field=models.FloatField(default=1.0, help_text='Layer alpha for alpha-over compositing (0..1)'),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='order',
            field=models.IntegerField(default=0, help_text='Explicit z-index for deterministic back-to-front compositing'),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='point_size',
            field=models.FloatField(blank=True, help_text='(point) The default point size, in scene units', null=True),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='render_graph',
            field=models.JSONField(blank=True, default=None, help_text='(image) Optional per-layer composable render recipe (channels + transfer functions + in-layer blend). If null, the flat colormap/clim/color fields describe a single-channel layer.', null=True),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='size_column',
            field=models.CharField(blank=True, help_text='(point) The table column mapped to per-point size', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='stroke_color',
            field=models.JSONField(blank=True, default=None, help_text='(shape) The stroke (outline) color of the geometry (RGBA)', null=True),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='stroke_width',
            field=models.FloatField(blank=True, help_text='(shape) The stroke width of the geometry, in scene units', null=True),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='t_column',
            field=models.CharField(blank=True, help_text='(point/track) The table column mapped to the time coordinate', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='table',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='(point/track) The table whose columns provide the coordinates and attributes', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.table'),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='track_id_column',
            field=models.CharField(blank=True, help_text='(track) The table column that groups rows into tracks', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='visible',
            field=models.BooleanField(default=True, help_text='Whether the layer participates in compositing'),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='wireframe',
            field=models.BooleanField(default=False, help_text='(mesh) Whether the mesh is rendered as a wireframe instead of a solid surface'),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='x_column',
            field=models.CharField(blank=True, help_text='(point/track) The table column mapped to the x coordinate', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='y_column',
            field=models.CharField(blank=True, help_text='(point/track) The table column mapped to the y coordinate', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='z_column',
            field=models.CharField(blank=True, help_text='(point/track) The table column mapped to the z coordinate', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='color_by_column',
            field=models.CharField(blank=True, help_text='(track) The table column used to color tracks (used with colormap)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='color_column',
            field=models.CharField(blank=True, help_text='(point) The table column mapped to per-point color/intensity (used with colormap)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='data_roi',
            field=models.ForeignKey(blank=True, help_text='(shape) The data ROI whose vectors this layer renders', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shape_layers', to='core.dataroi'),
        ),
        migrations.AddField(
            model_name='layer',
            name='fill_color',
            field=models.JSONField(blank=True, default=None, help_text='(shape) The fill color of the geometry (RGBA), or null for no fill', null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='filled',
            field=models.BooleanField(default=False, help_text='(shape) Whether the geometry is filled with fill_color'),
        ),
        migrations.AddField(
            model_name='layer',
            name='id_column',
            field=models.CharField(blank=True, help_text='(point) The table column identifying each point', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='kind',
            field=django_choices_field.fields.TextChoicesField(choices=[('image', 'Image (array data)'), ('shape', 'Shape (ROI geometry)'), ('point', 'Point (tabular point cloud)'), ('track', 'Track (tabular trajectories)'), ('mesh', 'Mesh (3D surface)')], choices_enum=core.enums.LayerKindChoices, default='image', help_text='The kind of layer, discriminating its data source and render settings', max_length=5),
        ),
        migrations.AddField(
            model_name='layer',
            name='line_width',
            field=models.FloatField(blank=True, help_text='(track) The width of the track lines, in scene units', null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='material_color',
            field=models.JSONField(blank=True, default=None, help_text='(mesh) The material (surface) color of the mesh (RGBA)', null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='mesh',
            field=models.ForeignKey(blank=True, help_text='(mesh) The mesh whose geometry this layer renders', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesh_layers', to='core.mesh'),
        ),
        migrations.AddField(
            model_name='layer',
            name='opacity',
            field=models.FloatField(default=1.0, help_text='Layer alpha for alpha-over compositing (0..1)'),
        ),
        migrations.AddField(
            model_name='layer',
            name='order',
            field=models.IntegerField(default=0, help_text='Explicit z-index for deterministic back-to-front compositing'),
        ),
        migrations.AddField(
            model_name='layer',
            name='point_size',
            field=models.FloatField(blank=True, help_text='(point) The default point size, in scene units', null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='render_graph',
            field=models.JSONField(blank=True, default=None, help_text='(image) Optional per-layer composable render recipe (channels + transfer functions + in-layer blend). If null, the flat colormap/clim/color fields describe a single-channel layer.', null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='size_column',
            field=models.CharField(blank=True, help_text='(point) The table column mapped to per-point size', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='stroke_color',
            field=models.JSONField(blank=True, default=None, help_text='(shape) The stroke (outline) color of the geometry (RGBA)', null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='stroke_width',
            field=models.FloatField(blank=True, help_text='(shape) The stroke width of the geometry, in scene units', null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='t_column',
            field=models.CharField(blank=True, help_text='(point/track) The table column mapped to the time coordinate', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='table',
            field=models.ForeignKey(blank=True, help_text='(point/track) The table whose columns provide the coordinates and attributes', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_layers', to='core.table'),
        ),
        migrations.AddField(
            model_name='layer',
            name='track_id_column',
            field=models.CharField(blank=True, help_text='(track) The table column that groups rows into tracks', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='visible',
            field=models.BooleanField(default=True, help_text='Whether the layer participates in compositing'),
        ),
        migrations.AddField(
            model_name='layer',
            name='wireframe',
            field=models.BooleanField(default=False, help_text='(mesh) Whether the mesh is rendered as a wireframe instead of a solid surface'),
        ),
        migrations.AddField(
            model_name='layer',
            name='x_column',
            field=models.CharField(blank=True, help_text='(point/track) The table column mapped to the x coordinate', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='y_column',
            field=models.CharField(blank=True, help_text='(point/track) The table column mapped to the y coordinate', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='z_column',
            field=models.CharField(blank=True, help_text='(point/track) The table column mapped to the z coordinate', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicallayer',
            name='blending',
            field=django_choices_field.fields.TextChoicesField(choices=[('additive', 'Additive'), ('multiplicative', 'Multiplicative'), ('normal', 'Normal (Alpha Over)')], choices_enum=core.enums.BlendingChoices, default='additive', help_text='The blending mode used to composite this layer over the layers below it', max_length=14),
        ),
        migrations.AlterField(
            model_name='historicallayer',
            name='clim_max',
            field=models.FloatField(blank=True, help_text='(image) The contrast limit max of the channel', null=True),
        ),
        migrations.AlterField(
            model_name='historicallayer',
            name='clim_min',
            field=models.FloatField(blank=True, help_text='(image) The contrast limit min of the channel', null=True),
        ),
        migrations.AlterField(
            model_name='historicallayer',
            name='color',
            field=models.JSONField(default=core.models.view.create_default_color, help_text='(image) The base color of the channel (if using a mapped scaler) (RGBA)', null=True),
        ),
        migrations.AlterField(
            model_name='historicallayer',
            name='colormap',
            field=django_choices_field.fields.TextChoicesField(blank=True, choices=[('viridis', 'Viridis'), ('plasma', 'Plasma'), ('inferno', 'Inferno'), ('magma', 'Magma'), ('red', 'Red'), ('green', 'Green'), ('blue', 'Blue'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('yellow', 'Yellow'), ('black', 'Black'), ('white', 'White'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('grey', 'Grey'), ('rainbow', 'Rainbow'), ('spectral', 'Spectral'), ('cool', 'Cool'), ('warm', 'Warm'), ('intensity', 'Intensity')], choices_enum=core.enums.ColorMapChoices, default='viridis', help_text='(image/point/track) The applying color map', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='historicallayer',
            name='gamma',
            field=models.FloatField(blank=True, help_text='(image) The gamma of the channel', null=True),
        ),
        migrations.AlterField(
            model_name='historicallayer',
            name='intensity_dim',
            field=models.CharField(blank=True, help_text='(image) The name of the intensity dimension in the data source', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicallayer',
            name='lens',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='(image) The lens that defines the array data source and constraints', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.lens'),
        ),
        migrations.AlterField(
            model_name='historicallayer',
            name='t_dim',
            field=models.CharField(blank=True, help_text='(image) The name of the t dimension in the data source', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicallayer',
            name='x_dim',
            field=models.CharField(blank=True, help_text='(image) The name of the x dimension in the data source', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicallayer',
            name='y_dim',
            field=models.CharField(blank=True, help_text='(image) The name of the y dimension in the data source', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicallayer',
            name='z_dim',
            field=models.CharField(blank=True, help_text='(image) The name of the z dimension in the data source', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='blending',
            field=django_choices_field.fields.TextChoicesField(choices=[('additive', 'Additive'), ('multiplicative', 'Multiplicative'), ('normal', 'Normal (Alpha Over)')], choices_enum=core.enums.BlendingChoices, default='additive', help_text='The blending mode used to composite this layer over the layers below it', max_length=14),
        ),
        migrations.AlterField(
            model_name='layer',
            name='clim_max',
            field=models.FloatField(blank=True, help_text='(image) The contrast limit max of the channel', null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='clim_min',
            field=models.FloatField(blank=True, help_text='(image) The contrast limit min of the channel', null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='color',
            field=models.JSONField(default=core.models.view.create_default_color, help_text='(image) The base color of the channel (if using a mapped scaler) (RGBA)', null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='colormap',
            field=django_choices_field.fields.TextChoicesField(blank=True, choices=[('viridis', 'Viridis'), ('plasma', 'Plasma'), ('inferno', 'Inferno'), ('magma', 'Magma'), ('red', 'Red'), ('green', 'Green'), ('blue', 'Blue'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('yellow', 'Yellow'), ('black', 'Black'), ('white', 'White'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('grey', 'Grey'), ('rainbow', 'Rainbow'), ('spectral', 'Spectral'), ('cool', 'Cool'), ('warm', 'Warm'), ('intensity', 'Intensity')], choices_enum=core.enums.ColorMapChoices, default='viridis', help_text='(image/point/track) The applying color map', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='gamma',
            field=models.FloatField(blank=True, help_text='(image) The gamma of the channel', null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='intensity_dim',
            field=models.CharField(blank=True, help_text='(image) The name of the intensity dimension in the data source', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='lens',
            field=models.ForeignKey(blank=True, help_text='(image) The lens that defines the array data source and constraints', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='core.lens'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='t_dim',
            field=models.CharField(blank=True, help_text='(image) The name of the t dimension in the data source', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='x_dim',
            field=models.CharField(blank=True, help_text='(image) The name of the x dimension in the data source', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='y_dim',
            field=models.CharField(blank=True, help_text='(image) The name of the y dimension in the data source', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='z_dim',
            field=models.CharField(blank=True, help_text='(image) The name of the z dimension in the data source', max_length=100, null=True),
        ),
    ]
