# Generated by Django 5.2 on 2026-05-07 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='The label of the channel', max_length=1000, null=True)),
                ('anchor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_labels', to='core.coordinateanchor')),
            ],
        ),
        migrations.CreateModel(
            name='LightPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.JSONField(default=dict)),
                ('anchor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightpath', to='core.coordinateanchor')),
            ],
        ),
    ]
