# Generated by Django 5.2 on 2025-07-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_channelview_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrgbview',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether the view is active'),
        ),
        migrations.AddField(
            model_name='rgbview',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether the view is active'),
        ),
    ]
