# Generated by Django 6.0.6 on 2026-07-07 09:30

import core.enums
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_flat_layer_kinds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallayer',
            name='clim_max',
        ),
        migrations.RemoveField(
            model_name='historicallayer',
            name='clim_min',
        ),
        migrations.RemoveField(
            model_name='historicallayer',
            name='color',
        ),
        migrations.RemoveField(
            model_name='historicallayer',
            name='gamma',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='clim_max',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='clim_min',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='color',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='gamma',
        ),
        migrations.AlterField(
            model_name='historicallayer',
            name='colormap',
            field=django_choices_field.fields.TextChoicesField(blank=True, choices=[('viridis', 'Viridis'), ('plasma', 'Plasma'), ('inferno', 'Inferno'), ('magma', 'Magma'), ('red', 'Red'), ('green', 'Green'), ('blue', 'Blue'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('yellow', 'Yellow'), ('black', 'Black'), ('white', 'White'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('grey', 'Grey'), ('rainbow', 'Rainbow'), ('spectral', 'Spectral'), ('cool', 'Cool'), ('warm', 'Warm'), ('intensity', 'Intensity')], choices_enum=core.enums.ColorMapChoices, default='viridis', help_text='(point/track) The applying color map', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='historicallayer',
            name='render_graph',
            field=models.JSONField(blank=True, default=None, help_text='(image) The composable render recipe (channels + transfer functions + in-layer blend) that is the single source of truth for how the image layer is rendered.', null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='colormap',
            field=django_choices_field.fields.TextChoicesField(blank=True, choices=[('viridis', 'Viridis'), ('plasma', 'Plasma'), ('inferno', 'Inferno'), ('magma', 'Magma'), ('red', 'Red'), ('green', 'Green'), ('blue', 'Blue'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('yellow', 'Yellow'), ('black', 'Black'), ('white', 'White'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('grey', 'Grey'), ('rainbow', 'Rainbow'), ('spectral', 'Spectral'), ('cool', 'Cool'), ('warm', 'Warm'), ('intensity', 'Intensity')], choices_enum=core.enums.ColorMapChoices, default='viridis', help_text='(point/track) The applying color map', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='render_graph',
            field=models.JSONField(blank=True, default=None, help_text='(image) The composable render recipe (channels + transfer functions + in-layer blend) that is the single source of truth for how the image layer is rendered.', null=True),
        ),
    ]
