# Generated by Django 4.2.3 on 2023-08-01 14:18

from django.db import migrations
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_imageintmetric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageintmetric",
            name="image",
            field=simple_history.models.HistoricForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.image",
            ),
        ),
    ]
