# Generated by Django 5.2 on 2025-11-29 13:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_metaschema_historicalmetaschema_unstructuredmeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrgbview',
            name='base_color',
            field=models.JSONField(default=core.models.create_default_color, help_text='The base color of the channel (if using a mapped scaler) (RGBA)', null=True),
        ),
        migrations.AlterField(
            model_name='rgbview',
            name='base_color',
            field=models.JSONField(default=core.models.create_default_color, help_text='The base color of the channel (if using a mapped scaler) (RGBA)', null=True),
        ),
    ]
