# Generated by Django 4.2.8 on 2024-08-18 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_historicalprotocolstep_plate_children_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entity",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="historicalentity",
            name="parent",
        ),
    ]
