# Generated by Django 5.2 on 2025-07-17 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0001_initial'),
        ('core', '0003_dataset_description_two_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='authentikate.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization'),
        ),
    ]
