# Generated by Django 5.2 on 2025-09-10 17:25

from django.db import migrations, models
from core.logic.roi import update_roi_bounds

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_historicalrgbview_active_rgbview_active"),
    ]
    
    def calculate_all_roi_bounds(apps, schema_editor):
        """Calculate and populate bounds for all existing ROIs."""
        ROI = apps.get_model("core", "ROI")
        
        for roi in ROI.objects.all():
            update_roi_bounds(roi)
            roi.save()
        

    operations = [
        migrations.AddField(
            model_name="historicalroi",
            name="max_c",
            field=models.IntegerField(
                blank=True, help_text="The maximum c coordinate of the ROI", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalroi",
            name="max_t",
            field=models.IntegerField(
                blank=True, help_text="The maximum t coordinate of the ROI", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalroi",
            name="max_x",
            field=models.IntegerField(
                blank=True, help_text="The maximum x coordinate of the ROI", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalroi",
            name="max_y",
            field=models.IntegerField(
                blank=True, help_text="The maximum y coordinate of the ROI", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalroi",
            name="max_z",
            field=models.IntegerField(
                blank=True, help_text="The maximum z coordinate of the ROI", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalroi",
            name="min_c",
            field=models.IntegerField(
                blank=True, help_text="The minimum c coordinate of the ROI", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalroi",
            name="min_t",
            field=models.IntegerField(
                blank=True, help_text="The minimum t coordinate of the ROI", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalroi",
            name="min_x",
            field=models.IntegerField(
                blank=True, help_text="The minimum x coordinate of the ROI", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalroi",
            name="min_y",
            field=models.IntegerField(
                blank=True, help_text="The minimum y coordinate of the ROI", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalroi",
            name="min_z",
            field=models.IntegerField(
                blank=True, help_text="The minimum z coordinate of the ROI", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalsnapshot",
            name="major_color",
            field=models.JSONField(
                blank=True, help_text="The major color of the snapshot", null=True
            ),
        ),
        migrations.AddField(
            model_name="roi",
            name="max_c",
            field=models.IntegerField(
                blank=True, help_text="The maximum c coordinate of the ROI", null=True
            ),
        ),
        migrations.AddField(
            model_name="roi",
            name="max_t",
            field=models.IntegerField(
                blank=True, help_text="The maximum t coordinate of the ROI", null=True
            ),
        ),
        migrations.AddField(
            model_name="roi",
            name="max_x",
            field=models.IntegerField(
                blank=True, help_text="The maximum x coordinate of the ROI", null=True
            ),
        ),
        migrations.AddField(
            model_name="roi",
            name="max_y",
            field=models.IntegerField(
                blank=True, help_text="The maximum y coordinate of the ROI", null=True
            ),
        ),
        migrations.AddField(
            model_name="roi",
            name="max_z",
            field=models.IntegerField(
                blank=True, help_text="The maximum z coordinate of the ROI", null=True
            ),
        ),
        migrations.AddField(
            model_name="roi",
            name="min_c",
            field=models.IntegerField(
                blank=True, help_text="The minimum c coordinate of the ROI", null=True
            ),
        ),
        migrations.AddField(
            model_name="roi",
            name="min_t",
            field=models.IntegerField(
                blank=True, help_text="The minimum t coordinate of the ROI", null=True
            ),
        ),
        migrations.AddField(
            model_name="roi",
            name="min_x",
            field=models.IntegerField(
                blank=True, help_text="The minimum x coordinate of the ROI", null=True
            ),
        ),
        migrations.AddField(
            model_name="roi",
            name="min_y",
            field=models.IntegerField(
                blank=True, help_text="The minimum y coordinate of the ROI", null=True
            ),
        ),
        migrations.AddField(
            model_name="roi",
            name="min_z",
            field=models.IntegerField(
                blank=True, help_text="The minimum z coordinate of the ROI", null=True
            ),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="major_color",
            field=models.JSONField(
                blank=True, help_text="The major color of the snapshot", null=True
            ),
        ),
        migrations.RunPython(calculate_all_roi_bounds)
    ]
