# Generated by Django 4.2.8 on 2024-09-03 12:35

import core.enums
from django.db import migrations
import django_choices_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_ontology_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="expression",
            name="metric_kind",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("INT", "Integer"),
                    ("FLOAT", "Float"),
                    ("DATETIME", "Datetime"),
                    ("STRING", "String"),
                    ("BOOLEAN", "Boolean"),
                ],
                choices_enum=core.enums.MetricDataTypeChoices,
                default="FLOAT",
                help_text="The data type of the metric",
                max_length=8,
            ),
        ),
    ]
