# Generated by Django 5.2 on 2026-05-07 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_channellabel_lightpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channellabel',
            name='anchor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel_labels', to='core.coordinateanchor'),
        ),
        migrations.AlterField(
            model_name='lightpath',
            name='anchor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lightpath', to='core.coordinateanchor'),
        ),
        migrations.AlterField(
            model_name='omemetadata',
            name='anchor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ome_metadata', to='core.coordinateanchor'),
        ),
        migrations.AlterField(
            model_name='omeplanemetadata',
            name='anchor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ome_plane_metadata', to='core.coordinateanchor'),
        ),
        migrations.AlterField(
            model_name='valuehistogram',
            name='anchor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='value_histogram', to='core.coordinateanchor'),
        ),
    ]
