# Generated by Django 6.0.6 on 2026-08-19 18:42

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentikate", "0006_alter_app_identifier_alter_release_unique_together"),
        ("core", "0004_label_pickers"),
        ("datalayer", "0003_sparsestore"),
        ("koherent", "0003_rename_assignation_to_task"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SparseDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of this sparse dataset", max_length=1000
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="The description of this sparse dataset",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "provenance_metadata",
                    models.JSONField(
                        default=dict,
                        help_text="How this matrix was produced (the run, its parameters and its inputs)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time this sparse dataset was created",
                    ),
                ),
                (
                    "coordinate_system",
                    models.ForeignKey(
                        blank=True,
                        help_text="The coordinate system whose axes are this matrix's two enumerations. Owned by the dataset, and the space a FIELD edge lands in",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sparse_datasets",
                        to="core.coordinatesystem",
                    ),
                ),
                (
                    "created_through",
                    models.ForeignKey(
                        blank=True,
                        help_text="The task this object was created through, if any",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to="koherent.task",
                    ),
                ),
                (
                    "created_through_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The assigner of the creating task, denormalized for fast filtering",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user that created this sparse dataset",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        help_text="The folder this sparse dataset is filed in. Organisational only -- it says nothing about what its axes are or where they point",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sparse_datasets",
                        to="core.folder",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The organization this sparse dataset belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentikate.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalSparseDataset",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of this sparse dataset", max_length=1000
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="The description of this sparse dataset",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "provenance_metadata",
                    models.JSONField(
                        default=dict,
                        help_text="How this matrix was produced (the run, its parameters and its inputs)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="The time this sparse dataset was created",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authentikate.client",
                    ),
                ),
                (
                    "coordinate_system",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The coordinate system whose axes are this matrix's two enumerations. Owned by the dataset, and the space a FIELD edge lands in",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.coordinatesystem",
                    ),
                ),
                (
                    "created_through",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The task this object was created through, if any",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="koherent.task",
                    ),
                ),
                (
                    "created_through_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The assigner of the creating task, denormalized for fast filtering",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The user that created this sparse dataset",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The folder this sparse dataset is filed in. Organisational only -- it says nothing about what its axes are or where they point",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.folder",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The organization this sparse dataset belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="authentikate.organization",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        help_text="The task during which the change occurred, if any",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="koherent.task",
                    ),
                ),
                (
                    "history_relation",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="provenance_entries",
                        to="core.sparsedataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical sparse dataset",
                "verbose_name_plural": "historical sparse datasets",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="SparseAxisReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "axis",
                    models.CharField(
                        help_text="The name of the axis being identified. One of the dataset's own",
                        max_length=32,
                    ),
                ),
                (
                    "references",
                    models.ForeignKey(
                        help_text="The table whose rows this axis' positions are. Keyed by its single INDEX coordinate column, which is where a position is looked up -- the same contract `TableColumn.references` carries",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referenced_by_sparse_axes",
                        to="core.tabledataset",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="axis_references",
                        to="core.sparsedataset",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dataset", "axis"), name="one_reference_per_sparse_axis"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SparseArray",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indexed_axis",
                    models.PositiveSmallIntegerField(
                        help_text="Which axis of the dataset this store's `indptr` indexes, as a position in the declared axis order. Derived from the store's own `encoding-type` at creation -- `csr_matrix` indexes axis 0, `csc_matrix` axis 1 -- never supplied by a caller, because it *is* the encoding and a second statement of it could disagree with the bytes"
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        help_text="The zarr group holding this layout. Its encoding, shape and chunking were read from the artifact when its upload was finished",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sparse_arrays",
                        to="datalayer.sparsestore",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrays",
                        to="core.sparsedataset",
                    ),
                ),
            ],
            options={
                "ordering": ["indexed_axis"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dataset", "indexed_axis"),
                        name="one_sparse_array_per_indexed_axis",
                    )
                ],
            },
        ),
    ]
