# Generated by Django 6.0.6 on 2026-08-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_table_column_unit_on_measurements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='intrinsic_bbox',
            field=models.JSONField(blank=True, help_text="The annotation's axis-aligned bounding box in the frame its collection names (`bbox_system`, null meaning the collection's own space), as {'min': [...], 'max': [...]}. That frame is the nearest intrinsic space the collection's chain composes down to, which for a collection registered into a world, or derived across a rank change, is its own drawing space -- an edge that says nothing about an axis cannot be crossed to invent an extent along it. Derived from all corners of the geometry, never from min/max alone", null=True),
        ),
        migrations.AlterField(
            model_name='historicalannotation',
            name='intrinsic_bbox',
            field=models.JSONField(blank=True, help_text="The annotation's axis-aligned bounding box in the frame its collection names (`bbox_system`, null meaning the collection's own space), as {'min': [...], 'max': [...]}. That frame is the nearest intrinsic space the collection's chain composes down to, which for a collection registered into a world, or derived across a rank change, is its own drawing space -- an edge that says nothing about an axis cannot be crossed to invent an extent along it. Derived from all corners of the geometry, never from min/max alone", null=True),
        ),
    ]
