# Generated by Django 4.2.8 on 2024-09-03 12:37

import core.enums
from django.db import migrations
import django_choices_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_expression_metric_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expression",
            name="metric_kind",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("INT", "Integer"),
                    ("FLOAT", "Float"),
                    ("DATETIME", "Datetime"),
                    ("STRING", "String"),
                    ("BOOLEAN", "Boolean"),
                ],
                choices_enum=core.enums.MetricDataTypeChoices,
                help_text="The data type (if a metric)",
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="linkedexpression",
            name="metric_kind",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("INT", "Integer"),
                    ("FLOAT", "Float"),
                    ("DATETIME", "Datetime"),
                    ("STRING", "String"),
                    ("BOOLEAN", "Boolean"),
                ],
                choices_enum=core.enums.MetricDataTypeChoices,
                help_text="The data type (if a metric)",
                max_length=8,
                null=True,
            ),
        ),
    ]
