# Generated by Django 4.2.8 on 2025-02-05 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_meshstore_mesh"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mesh",
            name="creator",
        ),
    ]
