# Generated by Django 5.2 on 2026-06-12 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_channellabel_anchor_alter_lightpath_anchor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channellabel',
            name='anchor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel_label', to='core.coordinateanchor'),
        ),
        migrations.AlterField(
            model_name='lightpath',
            name='anchor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='light_graph', to='core.coordinateanchor'),
        ),
    ]
