# Generated by Django 4.2.8 on 2024-07-29 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_entitygroup_historicalentitygroup_entity_group_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entitykind",
            options={"default_related_name": "entity_kinds"},
        ),
        migrations.RemoveField(
            model_name="entitykind",
            name="is_roughly_equivalent_to",
        ),
        migrations.RemoveField(
            model_name="ontology",
            name="default",
        ),
        migrations.RemoveField(
            model_name="ontology",
            name="public_url",
        ),
        migrations.AddField(
            model_name="entitykind",
            name="purl",
            field=models.CharField(
                help_text="The PURL of the entity class", max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="ontology",
            name="default_for",
            field=models.ManyToManyField(
                blank=True,
                help_text="The users that have this ontology as default",
                related_name="default_ontologies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ontology",
            name="purl",
            field=models.CharField(
                help_text="The PURL of the ontology", max_length=1000, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="entitykind",
            constraint=models.UniqueConstraint(
                fields=("ontology", "label"), name="unique_entity_kind_ontology_label"
            ),
        ),
    ]
