# Generated by Django 6.0.6 on 2026-08-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_intensity_layer_tint'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='faces',
            field=models.JSONField(blank=True, default=None, help_text='(surface) The triangle topology, as index triples into `vectors`. Null for every kind whose vectors are read directly as a shape', null=True),
        ),
        migrations.AddField(
            model_name='historicalannotation',
            name='faces',
            field=models.JSONField(blank=True, default=None, help_text='(surface) The triangle topology, as index triples into `vectors`. Null for every kind whose vectors are read directly as a shape', null=True),
        ),
    ]
