# Generated by Django 4.2.8 on 2024-07-29 11:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_entitykind_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="entity",
            name="unique_entity_kind_name",
        ),
        migrations.AddField(
            model_name="entity",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="The time the entity was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="entitygroup",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="The image this entity group belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entity_groups",
                to="core.image",
            ),
        ),
        migrations.AddField(
            model_name="historicalentity",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                help_text="The time the entity was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalentitygroup",
            name="image",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The image this entity group belongs to",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.image",
            ),
        ),
        migrations.AddConstraint(
            model_name="entity",
            constraint=models.UniqueConstraint(
                fields=("group", "name"), name="unique_entity_kind_name"
            ),
        ),
    ]
