# Generated by Django 4.2.3 on 2023-08-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_imageintmetric_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="file_origins",
            field=models.ManyToManyField(related_name="derived_images", to="core.file"),
        ),
        migrations.AddField(
            model_name="image",
            name="roi_origins",
            field=models.ManyToManyField(related_name="derived_rois", to="core.roi"),
        ),
    ]
