# Generated by Django 4.2.8 on 2024-08-19 09:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_entityrelation_only_one_relation_per_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="entitykind",
            name="color",
            field=models.JSONField(
                default=core.models.random_color,
                help_text="The color of the entity class as RGB",
                max_length=1000,
            ),
        ),
    ]
