# Generated by Django 4.2.3 on 2023-07-31 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0005_mediastore"),
    ]

    operations = [
        migrations.CreateModel(
            name="Thumbnail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", help_text="The name of the file", max_length=1000
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnails",
                        to="core.dataset",
                    ),
                ),
                (
                    "origins",
                    models.ManyToManyField(related_name="derived", to="core.thumbnail"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        help_text="The store of the file",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.mediastore",
                    ),
                ),
            ],
        ),
    ]
