# Generated by Django 6.0.6 on 2026-07-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('core', '0005_physical_quantities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='camera',
            name='serial_number',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicalcamera',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicalcamera',
            name='serial_number',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicalinstrument',
            name='serial_number',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicalobjective',
            name='serial_number',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='serial_number',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='objective',
            name='serial_number',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterUniqueTogether(
            name='camera',
            unique_together={('serial_number', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='instrument',
            unique_together={('serial_number', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='objective',
            unique_together={('serial_number', 'organization')},
        ),
    ]
