# Generated by Django 6.0.6 on 2026-08-20 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sparsedataset_historicalsparsedataset_and_more'),
        ('datalayer', '0004_remove_sparsestore_chunks_remove_sparsestore_dtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparsearray',
            name='path',
            # Only to satisfy the schema change; a SparseArray with no path is meaningless, so the
            # default does not survive into the model. Every existing row was cleared first.
            preserve_default=False,
            field=models.CharField(default='', help_text="Where this layout sits inside the store's prefix, e.g. `layouts/csr_matrix`. A reader opens the group at this path, not the store root. Taken from the store's own block at creation -- the writer states which layouts it finished, and a name with nothing behind it was refused before the store was ever registerable", max_length=255),
        ),
        migrations.AlterField(
            model_name='sparsearray',
            name='indexed_axis',
            field=models.PositiveSmallIntegerField(help_text="Which axis of the dataset this layout makes contiguous, as a position in the declared axis order. Read from the store's own block at creation and never supplied by a caller: it is what the layout *is*, and a second statement of it could disagree with the bytes. Two axes is one case -- an array of rank n has up to n layouts, one per axis a reader might select along"),
        ),
        migrations.AlterField(
            model_name='sparsearray',
            name='store',
            field=models.ForeignKey(help_text='The store holding this layout. Its spec, shape and per-layout chunking were read from the artifact when its upload was finished. Both layouts of one matrix share it', on_delete=django.db.models.deletion.CASCADE, related_name='sparse_arrays', to='datalayer.sparsestore'),
        ),
    ]
