# Generated by Django 5.2 on 2025-09-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lightpathview_historicallightpathview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicallightpathview',
            old_name='lightpath',
            new_name='graph',
        ),
        migrations.RenameField(
            model_name='lightpathview',
            old_name='lightpath',
            new_name='graph',
        ),
    ]
