# Generated by Django 4.2.8 on 2024-09-03 12:41

import core.enums
from django.db import migrations
import django_choices_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_expression_metric_kind_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expression",
            name="metric_kind",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("INT", "Int"),
                    ("FLOAT", "Float"),
                    ("DATETIME", "Datetime"),
                    ("STRING", "String"),
                    ("CATEGORY", "Category"),
                    ("BOOLEAN", "Boolean"),
                    ("THREE_D_VECTOR", "Three D Vector"),
                    ("TWO_D_VECTOR", "Two D Vector"),
                    ("ONE_D_VECTOR", "One D Vector"),
                    ("FOUR_D_VECTOR", "Four D Vector"),
                    ("N_VECTOR", "N Vector"),
                ],
                choices_enum=core.enums.MetricDataTypeChoices,
                help_text="The data type (if a metric)",
                max_length=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="linkedexpression",
            name="metric_kind",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("INT", "Int"),
                    ("FLOAT", "Float"),
                    ("DATETIME", "Datetime"),
                    ("STRING", "String"),
                    ("CATEGORY", "Category"),
                    ("BOOLEAN", "Boolean"),
                    ("THREE_D_VECTOR", "Three D Vector"),
                    ("TWO_D_VECTOR", "Two D Vector"),
                    ("ONE_D_VECTOR", "One D Vector"),
                    ("FOUR_D_VECTOR", "Four D Vector"),
                    ("N_VECTOR", "N Vector"),
                ],
                choices_enum=core.enums.MetricDataTypeChoices,
                help_text="The data type (if a metric)",
                max_length=14,
                null=True,
            ),
        ),
    ]
