# Generated by Django 4.2.8 on 2024-08-19 09:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_entitykind_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entitykind",
            name="color",
            field=models.JSONField(
                default=core.models.random_color,
                help_text="The color of the entity class as RGB",
                max_length=1000,
                null=True,
            ),
        ),
    ]
