# Generated by Django 4.2.8 on 2024-09-09 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_alter_expression_metric_kind_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkedexpression",
            name="pinned_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="The users that pinned this Expression",
                related_name="pinned_linked_expressions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
