# Generated by Django 4.2.3 on 2023-08-01 14:37

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("core", "0006_image_file_origins_image_roi_origins"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
