# Generated by Django 6.0.6 on 2026-06-12 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_organization_scoping'),
        ('koherent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaladataset',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalaffinetransformationview',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalblurhash',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalcamera',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalchannelview',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicaldataset',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalderivedview',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalera',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalexperiment',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalfile',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalfileview',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalhistogramview',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalimage',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalinstancemaskview',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalinstrument',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicallabelview',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicallayer',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicallens',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicallightpathview',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicallineagelink',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalmetaschema',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalmultiwellplate',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalobjective',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalopticsview',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalreferenceview',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalrgbrendercontext',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalrgbview',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalroi',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalroigroup',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalroiview',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalscaleview',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalscene',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalsnapshot',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalstage',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicaltable',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicaltableview',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicaltimepointview',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalvideo',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalviewcollection',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalwellpositionview',
            name='assignation_id',
        ),
        migrations.AddField(
            model_name='adataset',
            name='created_through',
            field=models.ForeignKey(blank=True, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='blurhash',
            name='created_through',
            field=models.ForeignKey(blank=True, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='created_through',
            field=models.ForeignKey(blank=True, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='era',
            name='created_through',
            field=models.ForeignKey(blank=True, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='file',
            name='created_through',
            field=models.ForeignKey(blank=True, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicaladataset',
            name='created_through',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicaladataset',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalaffinetransformationview',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalblurhash',
            name='created_through',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalblurhash',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalcamera',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalchannelview',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicaldataset',
            name='created_through',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicaldataset',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalderivedview',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalera',
            name='created_through',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalera',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalexperiment',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='created_through',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalfileview',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalhistogramview',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalimage',
            name='created_through',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalimage',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalinstancemaskview',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalinstrument',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicallabelview',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicallens',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicallightpathview',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicallineagelink',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalmetaschema',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalmultiwellplate',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalobjective',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalopticsview',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalreferenceview',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalrgbrendercontext',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalrgbview',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalroi',
            name='created_through',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalroi',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalroigroup',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalroiview',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalscaleview',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalscene',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalsnapshot',
            name='created_through',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalsnapshot',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalstage',
            name='created_through',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalstage',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicaltable',
            name='created_through',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicaltable',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicaltableview',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicaltimepointview',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalvideo',
            name='created_through',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalvideo',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalviewcollection',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalwellpositionview',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='image',
            name='created_through',
            field=models.ForeignKey(blank=True, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='roi',
            name='created_through',
            field=models.ForeignKey(blank=True, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='created_through',
            field=models.ForeignKey(blank=True, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='stage',
            name='created_through',
            field=models.ForeignKey(blank=True, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='table',
            name='created_through',
            field=models.ForeignKey(blank=True, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='video',
            name='created_through',
            field=models.ForeignKey(blank=True, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to='koherent.task'),
        ),
    ]
