# Generated by Django 6.0.6 on 2026-06-12 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_task_provenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adataset',
            name='created_through_by',
            field=models.ForeignKey(blank=True, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blurhash',
            name='created_through_by',
            field=models.ForeignKey(blank=True, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataset',
            name='created_through_by',
            field=models.ForeignKey(blank=True, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='era',
            name='created_through_by',
            field=models.ForeignKey(blank=True, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='created_through_by',
            field=models.ForeignKey(blank=True, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaladataset',
            name='created_through_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalblurhash',
            name='created_through_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldataset',
            name='created_through_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalera',
            name='created_through_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='created_through_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalimage',
            name='created_through_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalroi',
            name='created_through_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsnapshot',
            name='created_through_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalstage',
            name='created_through_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltable',
            name='created_through_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalvideo',
            name='created_through_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='created_through_by',
            field=models.ForeignKey(blank=True, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roi',
            name='created_through_by',
            field=models.ForeignKey(blank=True, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='created_through_by',
            field=models.ForeignKey(blank=True, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stage',
            name='created_through_by',
            field=models.ForeignKey(blank=True, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='table',
            name='created_through_by',
            field=models.ForeignKey(blank=True, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='created_through_by',
            field=models.ForeignKey(blank=True, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
