# Generated by Django 4.2.8 on 2024-09-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_linkedexpression_pinned_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="graph",
            name="description",
            field=models.CharField(
                help_text="The description of the entity group",
                max_length=2000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalgraph",
            name="description",
            field=models.CharField(
                help_text="The description of the entity group",
                max_length=2000,
                null=True,
            ),
        ),
    ]
