# Generated by Django 6.0.6 on 2026-07-13 15:24

import core.enums
import django.db.models.deletion
import django_choices_field.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('core', '0007_purge_array_domain'),
        ('datalayer', '0001_initial'),
        ('koherent', '0003_rename_assignation_to_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adataset',
            name='dim_descriptors',
        ),
        migrations.RemoveField(
            model_name='adataset',
            name='dims',
        ),
        migrations.RemoveField(
            model_name='adataset',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='dataarray',
            name='scale_factors',
        ),
        migrations.RemoveField(
            model_name='dataroi',
            name='constraints',
        ),
        migrations.RemoveField(
            model_name='dataroi',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='dataroi',
            name='x_dim',
        ),
        migrations.RemoveField(
            model_name='dataroi',
            name='x_max',
        ),
        migrations.RemoveField(
            model_name='dataroi',
            name='x_min',
        ),
        migrations.RemoveField(
            model_name='dataroi',
            name='y_dim',
        ),
        migrations.RemoveField(
            model_name='dataroi',
            name='y_max',
        ),
        migrations.RemoveField(
            model_name='dataroi',
            name='y_min',
        ),
        migrations.RemoveField(
            model_name='dataroi',
            name='z_dim',
        ),
        migrations.RemoveField(
            model_name='dataroi',
            name='z_max',
        ),
        migrations.RemoveField(
            model_name='dataroi',
            name='z_min',
        ),
        migrations.RemoveField(
            model_name='historicaladataset',
            name='dim_descriptors',
        ),
        migrations.RemoveField(
            model_name='historicaladataset',
            name='dims',
        ),
        migrations.RemoveField(
            model_name='historicaladataset',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='historicaldataroi',
            name='constraints',
        ),
        migrations.RemoveField(
            model_name='historicaldataroi',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='historicaldataroi',
            name='x_dim',
        ),
        migrations.RemoveField(
            model_name='historicaldataroi',
            name='x_max',
        ),
        migrations.RemoveField(
            model_name='historicaldataroi',
            name='x_min',
        ),
        migrations.RemoveField(
            model_name='historicaldataroi',
            name='y_dim',
        ),
        migrations.RemoveField(
            model_name='historicaldataroi',
            name='y_max',
        ),
        migrations.RemoveField(
            model_name='historicaldataroi',
            name='y_min',
        ),
        migrations.RemoveField(
            model_name='historicaldataroi',
            name='z_dim',
        ),
        migrations.RemoveField(
            model_name='historicaldataroi',
            name='z_max',
        ),
        migrations.RemoveField(
            model_name='historicaldataroi',
            name='z_min',
        ),
        migrations.RemoveField(
            model_name='historicallayer',
            name='affine_matrix',
        ),
        migrations.RemoveField(
            model_name='historicallayer',
            name='intensity_dim',
        ),
        migrations.RemoveField(
            model_name='historicallayer',
            name='t_dim',
        ),
        migrations.RemoveField(
            model_name='historicallayer',
            name='x_dim',
        ),
        migrations.RemoveField(
            model_name='historicallayer',
            name='y_dim',
        ),
        migrations.RemoveField(
            model_name='historicallayer',
            name='z_dim',
        ),
        migrations.RemoveField(
            model_name='historicallens',
            name='dim_descriptors',
        ),
        migrations.RemoveField(
            model_name='historicallens',
            name='dims',
        ),
        migrations.RemoveField(
            model_name='historicallens',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='historicalscene',
            name='affine_matrix',
        ),
        migrations.RemoveField(
            model_name='historicalscene',
            name='spatial_unit',
        ),
        migrations.RemoveField(
            model_name='historicalscene',
            name='temporal_unit',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='affine_matrix',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='intensity_dim',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='t_dim',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='x_dim',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='y_dim',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='z_dim',
        ),
        migrations.RemoveField(
            model_name='lens',
            name='dim_descriptors',
        ),
        migrations.RemoveField(
            model_name='lens',
            name='dims',
        ),
        migrations.RemoveField(
            model_name='lens',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='affine_matrix',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='spatial_unit',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='temporal_unit',
        ),
        migrations.AddField(
            model_name='adataset',
            name='multiscale',
            field=models.BooleanField(default=True, help_text='Whether this dataset carries a resolution pyramid (false for a single-level analysis array, e.g. a FLIM cube)'),
        ),
        migrations.AddField(
            model_name='dataroi',
            name='created_with_transforms',
            field=models.PositiveIntegerField(default=0, help_text='The version of the transformation chain this ROI was authored against. Provenance only: it is never used to resolve a coordinate'),
        ),
        migrations.AddField(
            model_name='dataroi',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='The user that drew this ROI', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_rois', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataroi',
            name='intrinsic_bbox',
            field=models.JSONField(blank=True, help_text="The ROI's axis-aligned bounding box in its dataset's intrinsic space, as {'min': [...], 'max': [...]}. Derived from all corners of the geometry, never from min/max alone", null=True),
        ),
        migrations.AddField(
            model_name='dataroi',
            name='selectors',
            field=models.JSONField(default=list, help_text="The discrete coordinates this ROI is pinned to, e.g. [{'axis': 't', 'index': 0}, {'axis': 'c', 'index': 0}]"),
        ),
        migrations.AddField(
            model_name='historicaladataset',
            name='multiscale',
            field=models.BooleanField(default=True, help_text='Whether this dataset carries a resolution pyramid (false for a single-level analysis array, e.g. a FLIM cube)'),
        ),
        migrations.AddField(
            model_name='historicaldataroi',
            name='created_with_transforms',
            field=models.PositiveIntegerField(default=0, help_text='The version of the transformation chain this ROI was authored against. Provenance only: it is never used to resolve a coordinate'),
        ),
        migrations.AddField(
            model_name='historicaldataroi',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The user that drew this ROI', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldataroi',
            name='intrinsic_bbox',
            field=models.JSONField(blank=True, help_text="The ROI's axis-aligned bounding box in its dataset's intrinsic space, as {'min': [...], 'max': [...]}. Derived from all corners of the geometry, never from min/max alone", null=True),
        ),
        migrations.AddField(
            model_name='historicaldataroi',
            name='selectors',
            field=models.JSONField(default=list, help_text="The discrete coordinates this ROI is pinned to, e.g. [{'axis': 't', 'index': 0}, {'axis': 'c', 'index': 0}]"),
        ),
        migrations.AlterField(
            model_name='dataroi',
            name='vectors',
            field=models.JSONField(default=list, help_text="A list of the ROI Vectors (specific for each type), in the coordinate system's own units"),
        ),
        migrations.AlterField(
            model_name='historicaldataroi',
            name='vectors',
            field=models.JSONField(default=list, help_text="A list of the ROI Vectors (specific for each type), in the coordinate system's own units"),
        ),
        migrations.AlterField(
            model_name='historicallens',
            name='slices',
            field=models.JSONField(default=list, help_text='The selection this lens makes over its dataset, as a list of per-dimension slices'),
        ),
        migrations.AlterField(
            model_name='lens',
            name='slices',
            field=models.JSONField(default=list, help_text='The selection this lens makes over its dataset, as a list of per-dimension slices'),
        ),
        migrations.CreateModel(
            name='CoordinateSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the coordinate system, unique within its container rather than globally', max_length=255)),
                ('kind', django_choices_field.fields.TextChoicesField(choices=[('ARRAY', 'Array (voxel index space of one pyramid level)'), ('INTRINSIC', "Intrinsic (the dataset's own physical space)"), ('WORLD', "World (a scene's shared space)"), ('ATLAS', 'Atlas (a shared reference space)')], choices_enum=core.enums.CoordinateSystemKindChoices, default='INTRINSIC', help_text="What this system denotes: voxel indices, a dataset's physical space, or a shared space", max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this coordinate system was created')),
                ('creator', models.ForeignKey(blank=True, help_text='The user that created this coordinate system', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('data_array', models.OneToOneField(blank=True, help_text='The pyramid level whose ARRAY (voxel index) space this is', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinate_system', to='core.dataarray')),
                ('dataset', models.ForeignKey(blank=True, help_text='The dataset whose INTRINSIC space this is', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinate_systems', to='core.adataset')),
                ('lens', models.OneToOneField(blank=True, help_text='The lens whose (cropped) space this is', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinate_system', to='core.lens')),
                ('organization', models.ForeignKey(help_text='The organization this coordinate system belongs to', on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization')),
                ('scene', models.OneToOneField(blank=True, help_text='The scene whose WORLD space this is', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_coordinate_system', to='core.scene')),
            ],
        ),
        migrations.CreateModel(
            name='Axis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='The index of this axis into the array shape')),
                ('name', models.CharField(help_text="The name of the axis, e.g. 'z', 'c' or 'tau'. Free-form", max_length=32)),
                ('type', django_choices_field.fields.TextChoicesField(choices=[('ARRAY', 'Array (raw voxel index)'), ('SPACE', 'Space'), ('TIME', 'Time'), ('CHANNEL', 'Channel'), ('COORDINATE', 'Coordinate'), ('DISPLACEMENT', 'Displacement'), ('MICROTIME', 'Microtime (FLIM arrival-time bin)')], choices_enum=core.enums.AxisTypeChoices, default='SPACE', help_text='The kind of the axis, which fixes its position in the RFC-5 axis ordering', max_length=12)),
                ('unit', models.CharField(blank=True, help_text="The physical unit of the axis, e.g. 'micrometer'. A pint unit (the kanne `Unit` scalar), validated on write; 'a.u.' for arbitrary units, null for discrete and index axes", max_length=64, null=True)),
                ('discrete', models.BooleanField(default=False, help_text="Whether the axis' coordinates are discrete indices rather than continuous positions")),
                ('long_name', models.CharField(blank=True, help_text='A human-readable name for the axis', max_length=255, null=True)),
                ('coordinate_system', models.ForeignKey(help_text='The coordinate system this axis belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='axes', to='core.coordinatesystem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='dataroi',
            name='coordinate_system',
            field=models.ForeignKey(help_text="The coordinate system this ROI's geometry is expressed in, normally a dataset's INTRINSIC system or a lens' system", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rois', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='historicaldataroi',
            name='coordinate_system',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="The coordinate system this ROI's geometry is expressed in, normally a dataset's INTRINSIC system or a lens' system", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.coordinatesystem'),
        ),
        migrations.CreateModel(
            name='HistoricalCoordinateSystem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the coordinate system, unique within its container rather than globally', max_length=255)),
                ('kind', django_choices_field.fields.TextChoicesField(choices=[('ARRAY', 'Array (voxel index space of one pyramid level)'), ('INTRINSIC', "Intrinsic (the dataset's own physical space)"), ('WORLD', "World (a scene's shared space)"), ('ATLAS', 'Atlas (a shared reference space)')], choices_enum=core.enums.CoordinateSystemKindChoices, default='INTRINSIC', help_text="What this system denotes: voxel indices, a dataset's physical space, or a shared space", max_length=9)),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='The time this coordinate system was created')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client')),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, help_text='The user that created this coordinate system', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('data_array', models.ForeignKey(blank=True, db_constraint=False, help_text='The pyramid level whose ARRAY (voxel index) space this is', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.dataarray')),
                ('dataset', models.ForeignKey(blank=True, db_constraint=False, help_text='The dataset whose INTRINSIC space this is', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.adataset')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.coordinatesystem')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lens', models.ForeignKey(blank=True, db_constraint=False, help_text='The lens whose (cropped) space this is', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.lens')),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, help_text='The organization this coordinate system belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization')),
                ('scene', models.ForeignKey(blank=True, db_constraint=False, help_text='The scene whose WORLD space this is', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.scene')),
                ('task', models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task')),
            ],
            options={
                'verbose_name': 'historical coordinate system',
                'verbose_name_plural': 'historical coordinate systems',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MeshCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text="The immutable version of this collection, e.g. 'v20260713-a3f9'", max_length=64)),
                ('spec_version', models.CharField(help_text='The version of the mesh encoding specification this collection conforms to', max_length=64)),
                ('grid', models.JSONField(default=dict, help_text="The octree grid, e.g. {'cellSize': [64, 64, 64], 'levels': 5, 'sortKey': 'MORTON'}. cellSize is in voxels of the coordinate system")),
                ('encoding', models.JSONField(default=dict, help_text="The geometry encoding, e.g. {'positions': 'UINT16_QUANTIZED_PER_CELL', 'normals': 'OCT16', 'indices': 'UINT16', 'codec': 'MESHOPT', 'compression': 'ZSTD'}")),
                ('provenance_metadata', models.JSONField(default=dict, help_text='How this collection was produced (the extraction run, its parameters and its inputs)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this mesh collection was created')),
                ('coordinate_system', models.ForeignKey(help_text='The coordinate system the mesh geometry is expressed in, e.g. that of a label array', on_delete=django.db.models.deletion.CASCADE, related_name='mesh_collections', to='core.coordinatesystem')),
                ('catalog', models.ForeignKey(help_text='The Parquet store holding the catalog that describes the meshes in this collection. The client reads it directly with a datalayer access grant', on_delete=django.db.models.deletion.CASCADE, related_name='mesh_catalogs', to='datalayer.parquetstore')),
                ('geometry', models.ManyToManyField(blank=True, help_text="The Parquet stores holding the geometry shards. Sharded because a collection's geometry does not fit in one object, and a renderer only ever wants the cells in view", related_name='mesh_geometries', to='datalayer.parquetstore')),
                ('creator', models.ForeignKey(blank=True, help_text='The user that created this mesh collection', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization this mesh collection belongs to', on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMeshCollection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.CharField(help_text="The immutable version of this collection, e.g. 'v20260713-a3f9'", max_length=64)),
                ('spec_version', models.CharField(help_text='The version of the mesh encoding specification this collection conforms to', max_length=64)),
                ('grid', models.JSONField(default=dict, help_text="The octree grid, e.g. {'cellSize': [64, 64, 64], 'levels': 5, 'sortKey': 'MORTON'}. cellSize is in voxels of the coordinate system")),
                ('encoding', models.JSONField(default=dict, help_text="The geometry encoding, e.g. {'positions': 'UINT16_QUANTIZED_PER_CELL', 'normals': 'OCT16', 'indices': 'UINT16', 'codec': 'MESHOPT', 'compression': 'ZSTD'}")),
                ('provenance_metadata', models.JSONField(default=dict, help_text='How this collection was produced (the extraction run, its parameters and its inputs)')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='The time this mesh collection was created')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client')),
                ('coordinate_system', models.ForeignKey(blank=True, db_constraint=False, help_text='The coordinate system the mesh geometry is expressed in, e.g. that of a label array', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.coordinatesystem')),
                ('catalog', models.ForeignKey(blank=True, db_constraint=False, help_text='The Parquet store holding the catalog that describes the meshes in this collection. The client reads it directly with a datalayer access grant', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datalayer.parquetstore')),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, help_text='The user that created this mesh collection', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, help_text='The organization this mesh collection belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization')),
                ('task', models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.meshcollection')),
            ],
            options={
                'verbose_name': 'historical mesh collection',
                'verbose_name_plural': 'historical mesh collections',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='mesh_collection',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='(mesh) The versioned, coordinate-system-anchored mesh collection this layer renders', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.meshcollection'),
        ),
        migrations.AddField(
            model_name='layer',
            name='mesh_collection',
            field=models.ForeignKey(blank=True, help_text='(mesh) The versioned, coordinate-system-anchored mesh collection this layer renders', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesh_layers', to='core.meshcollection'),
        ),
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', django_choices_field.fields.TextChoicesField(choices=[('IDENTITY', 'Identity'), ('SCALE', 'Scale'), ('TRANSLATION', 'Translation'), ('MAP_AXIS', 'Map Axis'), ('AFFINE', 'Affine'), ('ROTATION', 'Rotation'), ('SEQUENCE', 'Sequence'), ('BY_DIMENSION', 'By Dimension'), ('DISPLACEMENTS', 'Displacements'), ('BIJECTION', 'Bijection')], choices_enum=core.enums.TransformKindChoices, default='IDENTITY', help_text='The kind of transformation, which fixes how `params` is interpreted', max_length=13)),
                ('name', models.CharField(blank=True, help_text='The name of the transformation', max_length=255, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='The position of this child within its wrapping SEQUENCE, applied first to last')),
                ('input_axes', models.JSONField(blank=True, help_text="(byDimension) The names of the input axes this child acts on, e.g. ['z', 'y', 'x']", null=True)),
                ('output_axes', models.JSONField(blank=True, help_text='(byDimension) The names of the output axes this child produces', null=True)),
                ('params', models.JSONField(default=dict, help_text="The transformation's parameters, keyed by kind: SCALE {'scale': [...]}, TRANSLATION {'translation': [...]}, AFFINE {'affine': [[...], ...]} (M x (N+1), rows outermost), DISPLACEMENTS {'store_id': '...'}")),
                ('version', models.PositiveIntegerField(default=1, help_text="Incremented whenever this transformation's parameters are refined")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this transformation was created')),
                ('creator', models.ForeignKey(blank=True, help_text='The user that created this transformation', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('input', models.ForeignKey(blank=True, help_text='The coordinate system this transformation maps from', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.coordinatesystem')),
                ('organization', models.ForeignKey(help_text='The organization this transformation belongs to', on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization')),
                ('output', models.ForeignKey(blank=True, help_text='The coordinate system this transformation maps to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.coordinatesystem')),
                ('parent', models.ForeignKey(blank=True, help_text='The wrapping SEQUENCE / BY_DIMENSION / BIJECTION transformation, if this is a child', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.transformation')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTransformation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('kind', django_choices_field.fields.TextChoicesField(choices=[('IDENTITY', 'Identity'), ('SCALE', 'Scale'), ('TRANSLATION', 'Translation'), ('MAP_AXIS', 'Map Axis'), ('AFFINE', 'Affine'), ('ROTATION', 'Rotation'), ('SEQUENCE', 'Sequence'), ('BY_DIMENSION', 'By Dimension'), ('DISPLACEMENTS', 'Displacements'), ('BIJECTION', 'Bijection')], choices_enum=core.enums.TransformKindChoices, default='IDENTITY', help_text='The kind of transformation, which fixes how `params` is interpreted', max_length=13)),
                ('name', models.CharField(blank=True, help_text='The name of the transformation', max_length=255, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='The position of this child within its wrapping SEQUENCE, applied first to last')),
                ('input_axes', models.JSONField(blank=True, help_text="(byDimension) The names of the input axes this child acts on, e.g. ['z', 'y', 'x']", null=True)),
                ('output_axes', models.JSONField(blank=True, help_text='(byDimension) The names of the output axes this child produces', null=True)),
                ('params', models.JSONField(default=dict, help_text="The transformation's parameters, keyed by kind: SCALE {'scale': [...]}, TRANSLATION {'translation': [...]}, AFFINE {'affine': [[...], ...]} (M x (N+1), rows outermost), DISPLACEMENTS {'store_id': '...'}")),
                ('version', models.PositiveIntegerField(default=1, help_text="Incremented whenever this transformation's parameters are refined")),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='The time this transformation was created')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client')),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, help_text='The user that created this transformation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('input', models.ForeignKey(blank=True, db_constraint=False, help_text='The coordinate system this transformation maps from', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.coordinatesystem')),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, help_text='The organization this transformation belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization')),
                ('output', models.ForeignKey(blank=True, db_constraint=False, help_text='The coordinate system this transformation maps to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.coordinatesystem')),
                ('task', models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.transformation')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, help_text='The wrapping SEQUENCE / BY_DIMENSION / BIJECTION transformation, if this is a child', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.transformation')),
            ],
            options={
                'verbose_name': 'historical transformation',
                'verbose_name_plural': 'historical transformations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='scene',
            name='coordinate_transformations',
            field=models.ManyToManyField(blank=True, help_text="The transformation edges that belong to this scene, e.g. the registrations placing each layer's dataset into the scene's world system", related_name='scenes', to='core.transformation'),
        ),
        migrations.AddConstraint(
            model_name='coordinatesystem',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'INTRINSIC')), fields=('dataset',), name='one_intrinsic_system_per_dataset'),
        ),
        migrations.AlterUniqueTogether(
            name='axis',
            unique_together={('coordinate_system', 'name'), ('coordinate_system', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='meshcollection',
            unique_together={('coordinate_system', 'version')},
        ),
    ]
