# Generated by Django 4.2.8 on 2024-07-29 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0007_remove_ontology_default_for_ontology_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ontology",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="The user that this ontol",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ontology",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
