# Generated by Django 4.2.8 on 2025-03-20 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_histogramview_max_histogramview_min_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="histogramview",
            old_name="nbins",
            new_name="bins",
        ),
        migrations.RenameField(
            model_name="historicalhistogramview",
            old_name="nbins",
            new_name="bins",
        ),
    ]
