# Generated by Django 6.0.6 on 2026-06-13 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_created_through_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, help_text='The users that have pinned the camera', related_name='pinned_cameras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instrument',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, help_text='The users that have pinned the instrument', related_name='pinned_instruments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objective',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, help_text='The users that have pinned the objective', related_name='pinned_objectives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, help_text='The users that have pinned the snapshot', related_name='pinned_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='viewcollection',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, help_text='The users that have pinned the view collection', related_name='pinned_view_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
