# Generated by Django 4.2.8 on 2024-09-12 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_graph_description_historicalgraph_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expression",
            options={},
        ),
        migrations.AlterField(
            model_name="protocolstep",
            name="expression",
            field=models.ForeignKey(
                blank=True,
                help_text="The kind of the step. Think staining, imaging, etc.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.expression",
            ),
        ),
    ]
