# Generated by Django 6.0.6 on 2026-07-13 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rfc5_coordinate_systems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroi',
            name='coordinate_system',
            field=models.ForeignKey(help_text="The coordinate system this ROI's geometry is expressed in, normally a dataset's INTRINSIC system or a lens' system", on_delete=django.db.models.deletion.CASCADE, related_name='rois', to='core.coordinatesystem'),
        ),
    ]
