# Generated by Django 6.0.6 on 2026-06-15 18:20

import core.enums
import django.db.models.deletion
import django_choices_field.fields
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0005_alter_client_client_id'),
        ('core', '0009_camera_pinned_by_instrument_pinned_by_and_more'),
        ('koherent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroi',
            name='created_through',
            field=models.ForeignKey(blank=True, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='dataroi',
            name='created_through_by',
            field=models.ForeignKey(blank=True, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistoricalDataRoi',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('x_dim', models.CharField(help_text='The name of the x dimension in the data source', max_length=100)),
                ('y_dim', models.CharField(help_text='The name of the y dimension in the data source', max_length=100)),
                ('z_dim', models.CharField(blank=True, help_text='The name of the z dimension in the data source', max_length=100, null=True)),
                ('x_min', models.IntegerField(blank=True, help_text='The minimum x coordinate of the ROI', null=True)),
                ('x_max', models.IntegerField(blank=True, help_text='The maximum x coordinate of the ROI', null=True)),
                ('y_min', models.IntegerField(blank=True, help_text='The minimum y coordinate of the ROI', null=True)),
                ('y_max', models.IntegerField(blank=True, help_text='The maximum y coordinate of the ROI', null=True)),
                ('z_min', models.IntegerField(blank=True, help_text='The minimum z coordinate of the ROI', null=True)),
                ('z_max', models.IntegerField(blank=True, help_text='The maximum z coordinate of the ROI', null=True)),
                ('kind', django_choices_field.fields.TextChoicesField(choices=[('ellipse', 'Ellipse'), ('polygon', 'POLYGON'), ('line', 'Line'), ('rectangle', 'Rectangle (XY)'), ('spectral_rectangle', 'Spectral Rectangle (XYC)'), ('temporal_rectangle', 'Temporal Rectangle (XYT)'), ('cube', 'Cube (XYZ)'), ('spectral_cube', 'Spectral Cube (XYZC)'), ('temporal_cube', 'Temporal Cube (XYZT)'), ('hypercube', 'Hypercube (XYZT)'), ('spectral_hypercube', 'Spectral Hypercube (XYZTC)'), ('path', 'Path'), ('unknown', 'Unknown'), ('frame', 'Frame'), ('slice', 'Slice'), ('point', 'Point')], choices_enum=core.enums.RoiKindChoices, default='path', help_text='The Roi can have vasrying kind, consult your API', max_length=18)),
                ('constraints', models.JSONField(default=dict, help_text='The constraints of the ROI (for filtering data)')),
                ('vectors', models.JSONField(default=list, help_text='A list of the ROI Vectors (specific for each type)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client')),
                ('created_through', models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task')),
                ('created_through_by', models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.adataset')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.dataroi')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task')),
            ],
            options={
                'verbose_name': 'historical data roi',
                'verbose_name_plural': 'historical data rois',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
