# Generated by Django 4.2.8 on 2024-07-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_experiment_protocol_specimen_specimenview_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="instance_kind",
            field=models.CharField(
                blank=True,
                help_text="The instance kind of the entity",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalentity",
            name="instance_kind",
            field=models.CharField(
                blank=True,
                help_text="The instance kind of the entity",
                max_length=1000,
                null=True,
            ),
        ),
    ]
