# Generated by Django 4.2.8 on 2025-04-17 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentikate", "0002_alter_user_unique_together_and_more"),
        ("core", "0009_historicalfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="bigfilestore",
            name="filename",
            field=models.CharField(
                default="", help_text="The name of the file", max_length=1000
            ),
        ),
        migrations.AddField(
            model_name="bigfilestore",
            name="mimetype",
            field=models.CharField(
                default="", help_text="The mimetype of the file", max_length=1000
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="dataset",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="core.dataset",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="LocalHash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentikate.app",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
