# Generated by Django 6.0.6 on 2026-07-14 07:52

import core.enums
import django.db.models.deletion
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_dataroi_coordinate_system_required'),
        ('datalayer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coordinatesystem',
            name='one_intrinsic_system_per_dataset',
        ),
        migrations.RemoveField(
            model_name='adataset',
            name='multiscale',
        ),
        migrations.RemoveField(
            model_name='axis',
            name='discrete',
        ),
        migrations.RemoveField(
            model_name='historicaladataset',
            name='multiscale',
        ),
        migrations.AddField(
            model_name='coordinatesystem',
            name='intrinsic_of',
            field=models.OneToOneField(blank=True, help_text='The dataset whose INTRINSIC (level-0 pixel grid) space this is. One-to-one: the DB itself enforces one intrinsic system per dataset', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intrinsic_system', to='core.adataset'),
        ),
        migrations.AddField(
            model_name='historicalcoordinatesystem',
            name='intrinsic_of',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The dataset whose INTRINSIC (level-0 pixel grid) space this is. One-to-one: the DB itself enforces one intrinsic system per dataset', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.adataset'),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='coordinate_system',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="(point/track) The coordinate system the table's coordinate columns are expressed in. Without it a point cloud sits in an undefined space and cannot be registered through the graph", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='layer',
            name='coordinate_system',
            field=models.ForeignKey(blank=True, help_text="(point/track) The coordinate system the table's coordinate columns are expressed in. Without it a point cloud sits in an undefined space and cannot be registered through the graph", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anchored_layers', to='core.coordinatesystem'),
        ),
        migrations.AlterField(
            model_name='axis',
            name='type',
            field=django_choices_field.fields.TextChoicesField(choices=[('SPACE', 'Space'), ('TIME', 'Time'), ('CHANNEL', 'Channel'), ('COORDINATE', 'Coordinate'), ('DISPLACEMENT', 'Displacement'), ('MICROTIME', 'Microtime (FLIM arrival-time bin)')], choices_enum=core.enums.AxisTypeChoices, default='SPACE', help_text='The semantic kind of the axis, which fixes its position in the axis ordering and drives render-axis derivation', max_length=12),
        ),
        migrations.AlterField(
            model_name='axis',
            name='unit',
            field=models.CharField(blank=True, help_text="The physical unit of the axis, e.g. 'micrometer'. A pint unit (the kanne `Unit` scalar), validated on write; 'a.u.' for arbitrary units. Set on calibrated (PHYSICAL/WORLD/ATLAS) axes, always null on pixel (INTRINSIC/ARRAY) axes", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coordinateanchor',
            name='coordinates',
            field=models.JSONField(default=dict, help_text="The coordinates this anchor is pinned to, keyed by axis name, e.g. {'c': 0, 't': 5}. Level-0 pixel indices (the dataset's INTRINSIC space). An omitted axis means global along it"),
        ),
        migrations.AlterField(
            model_name='coordinatesystem',
            name='dataset',
            field=models.ForeignKey(blank=True, help_text='The dataset this PHYSICAL (calibrated) space belongs to. A dataset can carry many calibrations -- stage space, specimen space, a re-calibration -- and they cascade with it', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='core.adataset'),
        ),
        migrations.AlterField(
            model_name='coordinatesystem',
            name='kind',
            field=django_choices_field.fields.TextChoicesField(choices=[('ARRAY', 'Array (voxel index space of one pyramid level or lens)'), ('INTRINSIC', "Intrinsic (the dataset's level-0 pixel grid)"), ('PHYSICAL', 'Physical (a calibrated space derived from metadata)'), ('WORLD', "World (a scene's shared space)"), ('ATLAS', 'Atlas (a shared reference space)')], choices_enum=core.enums.CoordinateSystemKindChoices, default='INTRINSIC', help_text="What this system denotes: voxel indices, the dataset's pixel grid, a calibrated physical space, or a shared space", max_length=9),
        ),
        migrations.AlterField(
            model_name='dataarray',
            name='level',
            field=models.IntegerField(default=0, help_text='The level of the data array in the resolution pyramid, 0 being the highest resolution'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataroi',
            name='selectors',
            field=models.JSONField(default=dict, help_text="The discrete coordinates this ROI is pinned to, keyed by axis name, e.g. {'t': 0, 'c': 0}. An axis the ROI does not pin is one it spans"),
        ),
        migrations.AlterField(
            model_name='historicalcoordinatesystem',
            name='dataset',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The dataset this PHYSICAL (calibrated) space belongs to. A dataset can carry many calibrations -- stage space, specimen space, a re-calibration -- and they cascade with it', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.adataset'),
        ),
        migrations.AlterField(
            model_name='historicalcoordinatesystem',
            name='kind',
            field=django_choices_field.fields.TextChoicesField(choices=[('ARRAY', 'Array (voxel index space of one pyramid level or lens)'), ('INTRINSIC', "Intrinsic (the dataset's level-0 pixel grid)"), ('PHYSICAL', 'Physical (a calibrated space derived from metadata)'), ('WORLD', "World (a scene's shared space)"), ('ATLAS', 'Atlas (a shared reference space)')], choices_enum=core.enums.CoordinateSystemKindChoices, default='INTRINSIC', help_text="What this system denotes: voxel indices, the dataset's pixel grid, a calibrated physical space, or a shared space", max_length=9),
        ),
        migrations.AlterField(
            model_name='historicaldataroi',
            name='selectors',
            field=models.JSONField(default=dict, help_text="The discrete coordinates this ROI is pinned to, keyed by axis name, e.g. {'t': 0, 'c': 0}. An axis the ROI does not pin is one it spans"),
        ),
        migrations.AddConstraint(
            model_name='dataarray',
            constraint=models.UniqueConstraint(fields=('dataset', 'level'), name='one_data_array_per_level'),
        ),
    ]
