# Generated by Django 4.2.8 on 2024-09-12 09:59

import core.enums
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_choices_field.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0009_alter_expression_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reagent",
            name="concentration",
        ),
        migrations.RemoveField(
            model_name="reagent",
            name="entity",
        ),
        migrations.RemoveField(
            model_name="reagent",
            name="step",
        ),
        migrations.RemoveField(
            model_name="reagent",
            name="volume",
        ),
        migrations.AddField(
            model_name="historicalprotocol",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalprotocol",
            name="performed_at",
            field=models.DateTimeField(
                auto_created=True,
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalprotocol",
            name="reagent",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="This field is set if the protocol step is used to create another reagent",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.reagent",
            ),
        ),
        migrations.AddField(
            model_name="historicalprotocolstep",
            name="kind",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("PREP", "Preperation"),
                    ("MEASUREMENT", "Measurement"),
                    ("ANALYSIS", "Analysis"),
                    ("STORAGE", "Storage"),
                    ("UNKNOWN", "Unknown"),
                ],
                choices_enum=core.enums.ProtocolStepKindChoices,
                default="UNKNOWN",
                help_text="The kind of the step (can be more closely defined in the expression)",
                max_length=11,
            ),
        ),
        migrations.AddField(
            model_name="protocol",
            name="operator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="protocol",
            name="performed_at",
            field=models.DateTimeField(
                auto_created=True, auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="protocol",
            name="reagent",
            field=models.ForeignKey(
                help_text="This field is set if the protocol step is used to create another reagent",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="core.reagent",
            ),
        ),
        migrations.AddField(
            model_name="protocolstep",
            name="kind",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("PREP", "Preperation"),
                    ("MEASUREMENT", "Measurement"),
                    ("ANALYSIS", "Analysis"),
                    ("STORAGE", "Storage"),
                    ("UNKNOWN", "Unknown"),
                ],
                choices_enum=core.enums.ProtocolStepKindChoices,
                default="UNKNOWN",
                help_text="The kind of the step (can be more closely defined in the expression)",
                max_length=11,
            ),
        ),
        migrations.AddField(
            model_name="reagent",
            name="lot_number",
            field=models.CharField(
                blank=True,
                help_text="The lot number of the reagent",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reagent",
            name="mass",
            field=models.FloatField(
                blank=True,
                help_text="The mass of the reagent in the protocol",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reagent",
            name="order_id",
            field=models.CharField(
                blank=True,
                help_text="The order id of the reagent",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="experiment",
            field=models.ForeignKey(
                help_text="The experiment that this protocol was designed for",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protocols",
                to="core.experiment",
            ),
        ),
        migrations.AlterField(
            model_name="protocolstepmapping",
            name="t",
            field=models.IntegerField(
                blank=True,
                help_text="The relative time of the step according to the step of the protocol",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reagent",
            name="expression",
            field=models.ForeignKey(
                blank=True,
                help_text="The type of reagent (based on an ontology)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.expression",
            ),
        ),
        migrations.CreateModel(
            name="ReagentMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "volume",
                    models.FloatField(
                        blank=True,
                        help_text="The volume of the reagent in the protocol in µl",
                        null=True,
                    ),
                ),
                (
                    "reagent",
                    models.ForeignKey(
                        help_text="The reagent that this mapping is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="core.reagent",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        help_text="The step that this mapping is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reagents",
                        to="core.protocolstep",
                    ),
                ),
            ],
        ),
    ]
