# Generated by Django 6.0.6 on 2026-07-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pixel_intrinsic_and_calibrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscene',
            name='epoch',
            field=models.DateTimeField(blank=True, help_text="The wall-clock instant the world system's time axis has its origin at, so that `wall_clock = epoch + t * unit`. The time axis itself stays a relative coordinate, like every other axis -- this is the one place absolute time enters, and it is optional: a scene whose acquisition time is unknown has an unanchored, still perfectly composable, clock", null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='epoch',
            field=models.DateTimeField(blank=True, help_text="The wall-clock instant the world system's time axis has its origin at, so that `wall_clock = epoch + t * unit`. The time axis itself stays a relative coordinate, like every other axis -- this is the one place absolute time enters, and it is optional: a scene whose acquisition time is unknown has an unanchored, still perfectly composable, clock", null=True),
        ),
        migrations.AddConstraint(
            model_name='axis',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'TIME')), fields=('coordinate_system',), name='one_time_axis_per_coordinate_system'),
        ),
    ]
