# Generated by Django 4.2.8 on 2024-07-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_entity_instance_kind_historicalentity_instance_kind"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="entity",
            name="unique_entity_kind_name",
        ),
        migrations.AddConstraint(
            model_name="entity",
            constraint=models.UniqueConstraint(
                fields=("group", "name", "kind"), name="unique_entity_kind_name"
            ),
        ),
    ]
