# Generated by Django 4.2.8 on 2025-04-17 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_bigfilestore_filename_bigfilestore_mimetype_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bigfilestore",
            old_name="filename",
            new_name="file_name",
        ),
        migrations.RenameField(
            model_name="bigfilestore",
            old_name="mimetype",
            new_name="mime_type",
        ),
    ]
