# Generated by Django 4.2.8 on 2024-07-31 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_remove_entity_unique_entity_kind_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalantibody",
            name="app",
        ),
        migrations.RemoveField(
            model_name="historicalantibody",
            name="history_relation",
        ),
        migrations.RemoveField(
            model_name="historicalantibody",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalfluorophore",
            name="app",
        ),
        migrations.RemoveField(
            model_name="historicalfluorophore",
            name="history_relation",
        ),
        migrations.RemoveField(
            model_name="historicalfluorophore",
            name="history_user",
        ),
        migrations.AlterField(
            model_name="historicallabelview",
            name="fluorophore",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.entity",
            ),
        ),
        migrations.AlterField(
            model_name="historicallabelview",
            name="primary_antibody",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.entity",
            ),
        ),
        migrations.AlterField(
            model_name="historicallabelview",
            name="secondary_antibody",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.entity",
            ),
        ),
        migrations.AlterField(
            model_name="labelview",
            name="fluorophore",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="core.entity",
            ),
        ),
        migrations.AlterField(
            model_name="labelview",
            name="primary_antibody",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primary_views",
                to="core.entity",
            ),
        ),
        migrations.AlterField(
            model_name="labelview",
            name="secondary_antibody",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secondary_views",
                to="core.entity",
            ),
        ),
        migrations.DeleteModel(
            name="Antibody",
        ),
        migrations.DeleteModel(
            name="Fluorophore",
        ),
        migrations.DeleteModel(
            name="HistoricalAntibody",
        ),
        migrations.DeleteModel(
            name="HistoricalFluorophore",
        ),
    ]
