# Generated by Django 6.0.6 on 2026-07-14 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_spatiotemporal_scenes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhasorCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dim', models.CharField(help_text="The axis the correction applies to, e.g. 'tau'", max_length=32)),
                ('harmonic', models.PositiveSmallIntegerField(default=1, help_text='The harmonic the correction applies at')),
                ('phase_offset', models.FloatField(blank=True, help_text="The phase correction in radians, added to each pixel's phase", null=True)),
                ('modulation_factor', models.FloatField(blank=True, help_text="The modulation correction, multiplied into each pixel's modulus", null=True)),
                ('reference', models.CharField(blank=True, help_text="What the correction was measured against, e.g. 'Rhodamine 6G, 4.1 ns'", max_length=255, null=True)),
                ('anchor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phasor_calibrations', to='core.coordinateanchor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('anchor', 'dim', 'harmonic'), name='unique_phasor_calibration')],
            },
        ),
        migrations.CreateModel(
            name='PhasorHistogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dim', models.CharField(help_text="The axis the phasor was taken over, e.g. 'tau'", max_length=32)),
                ('harmonic', models.PositiveSmallIntegerField(default=1, help_text='The harmonic the phasor was taken at')),
                ('bins', models.PositiveIntegerField(default=256, help_text='The resolution of the square (g, s) density grid')),
                ('g_min', models.FloatField(default=0.0, help_text='The lower g bound of the density grid')),
                ('g_max', models.FloatField(default=1.0, help_text='The upper g bound of the density grid')),
                ('s_min', models.FloatField(default=0.0, help_text='The lower s bound of the density grid')),
                ('s_max', models.FloatField(default=0.6, help_text='The upper s bound of the density grid')),
                ('counts', models.JSONField(default=list, help_text='The flattened bins x bins density, row-major with s outermost')),
                ('total', models.BigIntegerField(blank=True, help_text='The number of pixels that contributed, so counts can be normalized', null=True)),
                ('calibrated', models.BooleanField(default=False, help_text='Whether the g/s were reference-corrected when computed. An uncalibrated density is still a valid distribution, it is just not traceable to an absolute lifetime')),
                ('profile', models.JSONField(blank=True, default=list, help_text='The summed profile along the phasor axis (a decay for a MICROTIME axis, a spectrum for a SPECTRUM one), one value per bin. Calibration-free, so a client can sanity-check or recompute the transform')),
                ('anchor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phasor_histograms', to='core.coordinateanchor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('anchor', 'dim', 'harmonic'), name='unique_phasor_histogram')],
            },
        ),
    ]
