# Generated by Django 4.2.8 on 2024-09-23 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0012_alter_protocol_reagent_alter_reagent_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicallabelview",
            name="acquisition_mode",
        ),
        migrations.RemoveField(
            model_name="historicallabelview",
            name="fluorophore",
        ),
        migrations.RemoveField(
            model_name="historicallabelview",
            name="primary_antibody",
        ),
        migrations.RemoveField(
            model_name="historicallabelview",
            name="secondary_antibody",
        ),
        migrations.RemoveField(
            model_name="labelview",
            name="acquisition_mode",
        ),
        migrations.RemoveField(
            model_name="labelview",
            name="fluorophore",
        ),
        migrations.RemoveField(
            model_name="labelview",
            name="primary_antibody",
        ),
        migrations.RemoveField(
            model_name="labelview",
            name="secondary_antibody",
        ),
        migrations.AddField(
            model_name="historicallabelview",
            name="expression",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.expression",
            ),
        ),
        migrations.AddField(
            model_name="labelview",
            name="expression",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="label_views",
                to="core.expression",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ReagentView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "z_min",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "z_max",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "x_min",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "x_max",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "y_min",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "y_max",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "t_min",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "t_max",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "c_min",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "c_max",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "is_global",
                    models.BooleanField(
                        default=False, help_text="Whether the view is global or not"
                    ),
                ),
                (
                    "volume",
                    models.FloatField(
                        blank=True,
                        help_text="The volume of the reagent that was added in µl. If you add some mass of a reagent, you can use the mass field instead.",
                        null=True,
                    ),
                ),
                (
                    "mass",
                    models.FloatField(
                        blank=True,
                        help_text="The mass of the reagent in the protocol in µg. If you add some volume of a reagent, you can use the volume field instead.",
                        null=True,
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.viewcollection",
                    ),
                ),
                (
                    "image",
                    simple_history.models.HistoricForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.image"
                    ),
                ),
                (
                    "reagent",
                    models.ForeignKey(
                        help_text="The reagent that this view is for (e.g. the reagent that was added)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reagent_views",
                        to="core.reagent",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        help_text="The step that describes how the reagent was added",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reagent_views",
                        to="core.protocolstep",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProtocolStepSubjection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "performed_at",
                    models.DateTimeField(auto_created=True, auto_now_add=True),
                ),
                (
                    "entity_id",
                    models.CharField(
                        blank=True,
                        help_text="The entity that this mapping is for",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        help_text="The step that this mapping is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjections",
                        to="core.protocolstep",
                    ),
                ),
            ],
        ),
    ]
