# Generated by Django 6.0.6 on 2026-07-14 15:12

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('core', '0012_phasor'),
        ('datalayer', '0001_initial'),
        ('koherent', '0003_rename_assignation_to_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meshcollection',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='historicalmeshcollection',
            name='coordinate_system',
        ),
        migrations.AddField(
            model_name='coordinatesystem',
            name='mesh_collection',
            field=models.OneToOneField(blank=True, help_text='The mesh collection whose vertex space this is', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinate_system', to='core.meshcollection'),
        ),
        migrations.AddField(
            model_name='historicalcoordinatesystem',
            name='mesh_collection',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The mesh collection whose vertex space this is', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.meshcollection'),
        ),
        migrations.AddField(
            model_name='historicaltransformation',
            name='store',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='(DISPLACEMENTS / COORDINATES) The Zarr array holding the field: per-point offsets for DISPLACEMENTS, absolute positions for COORDINATES', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datalayer.zarrstore'),
        ),
        migrations.AddField(
            model_name='transformation',
            name='store',
            field=models.ForeignKey(blank=True, help_text='(DISPLACEMENTS / COORDINATES) The Zarr array holding the field: per-point offsets for DISPLACEMENTS, absolute positions for COORDINATES', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transformations', to='datalayer.zarrstore'),
        ),
        migrations.AlterField(
            model_name='historicaltransformation',
            name='params',
            field=models.JSONField(default=dict, help_text="The transformation's parameters, keyed by kind: SCALE {'scale': [...]}, TRANSLATION {'translation': [...]}, AFFINE {'affine': [[...], ...]} (M x (N+1), rows outermost), UNMAPPABLE {'reason': '...'} (optional, purely descriptive)"),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='params',
            field=models.JSONField(default=dict, help_text="The transformation's parameters, keyed by kind: SCALE {'scale': [...]}, TRANSLATION {'translation': [...]}, AFFINE {'affine': [[...], ...]} (M x (N+1), rows outermost), UNMAPPABLE {'reason': '...'} (optional, purely descriptive)"),
        ),
        migrations.CreateModel(
            name='FeatureCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of this collection, e.g. 'nuclei morphology'", max_length=255)),
                ('version', models.CharField(help_text='The immutable version of this collection. A recomputation is a new version, never an edit to an old one', max_length=64)),
                ('spec_version', models.CharField(blank=True, help_text='The version of the feature-table specification this collection conforms to', max_length=64, null=True)),
                ('provenance_metadata', models.JSONField(default=dict, help_text='How this table was produced (the measurement run, its parameters and its inputs)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this feature collection was created')),
                ('creator', models.ForeignKey(blank=True, help_text='The user that created this feature collection', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization this feature collection belongs to', on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization')),
                ('store', models.ForeignKey(help_text='The Parquet store holding the table. The client reads it directly with a datalayer access grant', on_delete=django.db.models.deletion.CASCADE, related_name='feature_collections', to='datalayer.parquetstore')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='coordinatesystem',
            name='feature_collection',
            field=models.OneToOneField(blank=True, help_text='The feature collection whose row space this is', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinate_system', to='core.featurecollection'),
        ),
        migrations.AddField(
            model_name='historicalcoordinatesystem',
            name='feature_collection',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The feature collection whose row space this is', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.featurecollection'),
        ),
        migrations.CreateModel(
            name='HistoricalFeatureCollection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of this collection, e.g. 'nuclei morphology'", max_length=255)),
                ('version', models.CharField(help_text='The immutable version of this collection. A recomputation is a new version, never an edit to an old one', max_length=64)),
                ('spec_version', models.CharField(blank=True, help_text='The version of the feature-table specification this collection conforms to', max_length=64, null=True)),
                ('provenance_metadata', models.JSONField(default=dict, help_text='How this table was produced (the measurement run, its parameters and its inputs)')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='The time this feature collection was created')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client')),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, help_text='The user that created this feature collection', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.featurecollection')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, help_text='The organization this feature collection belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization')),
                ('store', models.ForeignKey(blank=True, db_constraint=False, help_text='The Parquet store holding the table. The client reads it directly with a datalayer access grant', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datalayer.parquetstore')),
                ('task', models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task')),
            ],
            options={
                'verbose_name': 'historical feature collection',
                'verbose_name_plural': 'historical feature collections',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
