# Generated by Django 4.2.8 on 2024-09-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_remove_historicallabelview_acquisition_mode_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specimen",
            name="protocol",
        ),
        migrations.RemoveField(
            model_name="historicalspecimenview",
            name="specimen",
        ),
        migrations.RemoveField(
            model_name="historicalspecimenview",
            name="step",
        ),
        migrations.RemoveField(
            model_name="specimenview",
            name="specimen",
        ),
        migrations.RemoveField(
            model_name="specimenview",
            name="step",
        ),
        migrations.AddField(
            model_name="historicalspecimenview",
            name="entity_id",
            field=models.CharField(
                blank=True,
                help_text="The entity that this view is for",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="specimenview",
            name="entity_id",
            field=models.CharField(
                blank=True,
                help_text="The entity that this view is for",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="HistoricalSpecimen",
        ),
        migrations.DeleteModel(
            name="Specimen",
        ),
    ]
