# Generated by Django 4.2.8 on 2024-08-08 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_renderedplot_historicalrenderedplot"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.ForeignKey(
                        help_text="The type of the relation between the entities",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations",
                        to="core.entitykind",
                    ),
                ),
                (
                    "left",
                    models.ForeignKey(
                        help_text="The left entity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations",
                        to="core.entity",
                    ),
                ),
                (
                    "right",
                    models.ForeignKey(
                        help_text="The right entity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related",
                        to="core.entity",
                    ),
                ),
            ],
        ),
    ]
