# Generated by Django 4.2.8 on 2024-09-24 11:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        ("authentikate", "0002_alter_user_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0014_remove_specimen_protocol_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalProtocolStepView",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "assignation_id",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "z_min",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "z_max",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "x_min",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "x_max",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "y_min",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "y_max",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "t_min",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "t_max",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "c_min",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "c_max",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "is_global",
                    models.BooleanField(
                        default=False, help_text="Whether the view is global or not"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authentikate.app",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.viewcollection",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical protocol step view",
                "verbose_name_plural": "historical protocol step views",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ProtocolStepView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "z_min",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "z_max",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "x_min",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "x_max",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "y_min",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "y_max",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "t_min",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "t_max",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "c_min",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "c_max",
                    models.IntegerField(
                        blank=True, help_text="The index of the channel", null=True
                    ),
                ),
                (
                    "is_global",
                    models.BooleanField(
                        default=False, help_text="Whether the view is global or not"
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.viewcollection",
                    ),
                ),
                (
                    "image",
                    simple_history.models.HistoricForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.image"
                    ),
                ),
            ],
            options={
                "default_related_name": "protocol_step_views",
            },
        ),
        migrations.RemoveField(
            model_name="protocolstepsubjection",
            name="operator",
        ),
        migrations.RemoveField(
            model_name="protocolstepsubjection",
            name="step",
        ),
        migrations.RemoveField(
            model_name="reagentmapping",
            name="reagent",
        ),
        migrations.RemoveField(
            model_name="reagentmapping",
            name="step",
        ),
        migrations.RemoveField(
            model_name="reagentview",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="reagentview",
            name="image",
        ),
        migrations.RemoveField(
            model_name="reagentview",
            name="reagent",
        ),
        migrations.RemoveField(
            model_name="reagentview",
            name="step",
        ),
        migrations.RemoveField(
            model_name="historicalprotocolstep",
            name="name",
        ),
        migrations.RemoveField(
            model_name="historicalprotocolstep",
            name="plate_children",
        ),
        migrations.RemoveField(
            model_name="protocolstep",
            name="name",
        ),
        migrations.RemoveField(
            model_name="protocolstep",
            name="plate_children",
        ),
        migrations.AddField(
            model_name="historicalprotocolstep",
            name="for_entity_id",
            field=models.CharField(
                blank=True,
                help_text="The entity that this step is for",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalprotocolstep",
            name="for_reagent",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="This field is set if the protocol step is used to create another reagent",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.reagent",
            ),
        ),
        migrations.AddField(
            model_name="historicalprotocolstep",
            name="performed_at",
            field=models.DateTimeField(
                auto_created=True,
                blank=True,
                default=datetime.datetime(
                    2024, 9, 24, 11, 42, 0, 574890, tzinfo=datetime.timezone.utc
                ),
                editable=False,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalprotocolstep",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The user that performed the step",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalprotocolstep",
            name="used_entity_id",
            field=models.CharField(
                blank=True,
                help_text="The entity that was used in the step",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalprotocolstep",
            name="used_reagent",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="This field is set if the protocol step used a reagent",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.reagent",
            ),
        ),
        migrations.AddField(
            model_name="historicalprotocolstep",
            name="used_reagent_mass",
            field=models.FloatField(
                blank=True,
                help_text="The mass of the reagent in the protocol in µg. If you add some volume of a reagent, you can use the volume field instead.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalprotocolstep",
            name="used_reagent_volume",
            field=models.FloatField(
                blank=True,
                help_text="The volume of the reagent that was added in µl. If you add some mass of a reagent, you can use the mass field instead.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="protocolstep",
            name="for_entity_id",
            field=models.CharField(
                blank=True,
                help_text="The entity that this step is for",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="protocolstep",
            name="for_reagent",
            field=models.ForeignKey(
                help_text="This field is set if the protocol step is used to create another reagent",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creation_steps",
                to="core.reagent",
            ),
        ),
        migrations.AddField(
            model_name="protocolstep",
            name="performed_at",
            field=models.DateTimeField(
                auto_created=True, auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="protocolstep",
            name="performed_by",
            field=models.ForeignKey(
                help_text="The user that performed the step",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="protocolstep",
            name="used_entity_id",
            field=models.CharField(
                blank=True,
                help_text="The entity that was used in the step",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="protocolstep",
            name="used_reagent",
            field=models.ForeignKey(
                help_text="This field is set if the protocol step used a reagent",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="used_in",
                to="core.reagent",
            ),
        ),
        migrations.AddField(
            model_name="protocolstep",
            name="used_reagent_mass",
            field=models.FloatField(
                blank=True,
                help_text="The mass of the reagent in the protocol in µg. If you add some volume of a reagent, you can use the volume field instead.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="protocolstep",
            name="used_reagent_volume",
            field=models.FloatField(
                blank=True,
                help_text="The volume of the reagent that was added in µl. If you add some mass of a reagent, you can use the mass field instead.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalprotocolstep",
            name="description",
            field=models.CharField(
                help_text="Some additional information about the step, specific to its operation",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="protocolstep",
            name="description",
            field=models.CharField(
                help_text="Some additional information about the step, specific to its operation",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="ProtocolStepMapping",
        ),
        migrations.DeleteModel(
            name="ProtocolStepSubjection",
        ),
        migrations.DeleteModel(
            name="ReagentMapping",
        ),
        migrations.DeleteModel(
            name="ReagentView",
        ),
        migrations.AddField(
            model_name="protocolstepview",
            name="step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="core.protocolstep",
            ),
        ),
        migrations.AddField(
            model_name="historicalprotocolstepview",
            name="history_relation",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="provenance",
                to="core.protocolstepview",
            ),
        ),
        migrations.AddField(
            model_name="historicalprotocolstepview",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalprotocolstepview",
            name="image",
            field=simple_history.models.HistoricForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.image",
            ),
        ),
        migrations.AddField(
            model_name="historicalprotocolstepview",
            name="step",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.protocolstep",
            ),
        ),
    ]
