# Generated by Django 4.2.8 on 2024-08-08 13:01

import core.enums
from django.db import migrations, models
import django.db.models.deletion
import django_choices_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_entityrelation"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="metrics",
            field=models.JSONField(
                default=dict, help_text="Associated metrics of the entity"
            ),
        ),
        migrations.AddField(
            model_name="historicalentity",
            name="metrics",
            field=models.JSONField(
                default=dict, help_text="Associated metrics of the entity"
            ),
        ),
        migrations.CreateModel(
            name="EntityMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_kind",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("INT", "Integer"),
                            ("FLOAT", "Float"),
                            ("DATETIME", "Datetime"),
                            ("STRING", "String"),
                        ],
                        choices_enum=core.enums.MetricDataTypeChoices,
                        default="FLOAT",
                        help_text="The data type of the metric",
                        max_length=8,
                    ),
                ),
                (
                    "kind",
                    models.ForeignKey(
                        help_text="The type of the metric",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="core.entitykind",
                    ),
                ),
            ],
            options={
                "default_related_name": "metrics",
            },
        ),
    ]
