# Generated by Django 4.2.8 on 2024-09-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_historicalprotocolstepview_protocolstepview_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprotocolstep",
            name="name",
            field=models.CharField(
                default="", help_text="The name of the protocol step", max_length=1000
            ),
        ),
        migrations.AddField(
            model_name="protocolstep",
            name="name",
            field=models.CharField(
                default="", help_text="The name of the protocol step", max_length=1000
            ),
        ),
    ]
