# Generated by Django 4.2.8 on 2024-08-08 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_entity_metrics_historicalentity_metrics_entitymetric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entitymetric",
            name="kind",
            field=models.OneToOneField(
                help_text="The type of the metric",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metrics",
                to="core.entitykind",
            ),
        ),
    ]
