# Generated by Django 4.2.4 on 2023-10-10 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_acquisitionview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acquisitionview",
            options={"default_related_name": "acquisition_views"},
        ),
    ]
