# Generated by Django 4.2.4 on 2023-11-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_alter_acquisitionview_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmultiwellplate",
            name="columns",
            field=models.IntegerField(
                blank=True,
                help_text="The number of columns in the multiwell plate",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmultiwellplate",
            name="rows",
            field=models.IntegerField(
                blank=True,
                help_text="The number of rows in the multiwell plate",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="multiwellplate",
            name="columns",
            field=models.IntegerField(
                blank=True,
                help_text="The number of columns in the multiwell plate",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="multiwellplate",
            name="rows",
            field=models.IntegerField(
                blank=True,
                help_text="The number of rows in the multiwell plate",
                null=True,
            ),
        ),
    ]
