# Generated by Django 4.2.8 on 2024-05-21 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_alter_historicalmultiwellplate_columns_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="roi",
            old_name="representation",
            new_name="image",
        ),
    ]
