# Generated by Django 6.0.6 on 2026-07-15 08:56

import core.enums
import django.db.models.deletion
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_axis_naming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallayer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicallayer',
            name='validity',
        ),
        migrations.RemoveField(
            model_name='historicalscene',
            name='epoch',
        ),
        migrations.AddField(
            model_name='historicalcoordinatesystem',
            name='epoch',
            field=models.DateTimeField(blank=True, help_text="The wall-clock instant this system's time axis has its origin at, so that `wall_clock = epoch + t * unit`. A property of the *space*, not of any composition over it -- two scenes sharing one space cannot disagree about when its clock starts. Meaningful only for a calibrated system with a TIME axis (a WORLD, an ATLAS); optional even there: an unanchored clock is still a perfectly composable relative coordinate", null=True),
        ),
        migrations.AddField(
            model_name='historicaltransformation',
            name='validity',
            field=django_choices_field.fields.TextChoicesField(choices=[('MANUAL', 'Manual'), ('INFERRED', 'Inferred from Metadata'), ('VALIDATED', 'Validated by User'), ('UNKNOWN', 'Unknown')], choices_enum=core.enums.PlacementValidityChoices, default='VALIDATED', help_text='How much this map is actually known. VALIDATED is the default because most edges are derived by the server from shapes and slices -- exact by construction. A writer that merely reads metadata says INFERRED, one that records an authored registration says MANUAL, and an edge the server assumed says UNKNOWN', max_length=9),
        ),
        migrations.AlterField(
            model_name='historicallayer',
            name='mesh_collection',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='(mesh) The versioned mesh collection, owning its own coordinate system, that this layer renders', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.meshcollection'),
        ),
    ]
