# Generated by Django 4.2.8 on 2024-02-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_alter_historicalmultiwellplate_columns_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bigfilestore",
            name="content",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
