# Generated by Django 4.2.8 on 2024-05-27 10:06

import core.enums
from django.db import migrations, models
import django.db.models.deletion
import django_choices_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_rename_representation_roi_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalrgbview",
            name="b_scale",
        ),
        migrations.RemoveField(
            model_name="historicalrgbview",
            name="g_scale",
        ),
        migrations.RemoveField(
            model_name="historicalrgbview",
            name="r_scale",
        ),
        migrations.RemoveField(
            model_name="rgbview",
            name="b_scale",
        ),
        migrations.RemoveField(
            model_name="rgbview",
            name="g_scale",
        ),
        migrations.RemoveField(
            model_name="rgbview",
            name="r_scale",
        ),
        migrations.AddField(
            model_name="historicalrgbrendercontext",
            name="governed_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.image",
            ),
        ),
        migrations.AddField(
            model_name="historicalrgbview",
            name="color_map",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("viridis", "Viridis"),
                    ("plasma", "Plasma"),
                    ("inferno", "Inferno"),
                    ("magma", "Magma"),
                    ("red", "Red"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                ],
                choices_enum=core.enums.ColorMapChoices,
                default="viridis",
                help_text="The applying color map of the channel",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="historicalrgbview",
            name="contrast_limit_max",
            field=models.FloatField(
                blank=True, help_text="The limits of the channel", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalrgbview",
            name="contrast_limit_min",
            field=models.FloatField(
                blank=True, help_text="The limits of the channel", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalrgbview",
            name="gamma",
            field=models.FloatField(
                blank=True, help_text="The gamma of the channel", null=True
            ),
        ),
        migrations.AddField(
            model_name="rgbrendercontext",
            name="governed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rgb_contexts",
                to="core.image",
            ),
        ),
        migrations.AddField(
            model_name="rgbview",
            name="color_map",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("viridis", "Viridis"),
                    ("plasma", "Plasma"),
                    ("inferno", "Inferno"),
                    ("magma", "Magma"),
                    ("red", "Red"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                ],
                choices_enum=core.enums.ColorMapChoices,
                default="viridis",
                help_text="The applying color map of the channel",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="rgbview",
            name="contrast_limit_max",
            field=models.FloatField(
                blank=True, help_text="The limits of the channel", null=True
            ),
        ),
        migrations.AddField(
            model_name="rgbview",
            name="contrast_limit_min",
            field=models.FloatField(
                blank=True, help_text="The limits of the channel", null=True
            ),
        ),
        migrations.AddField(
            model_name="rgbview",
            name="gamma",
            field=models.FloatField(
                blank=True, help_text="The gamma of the channel", null=True
            ),
        ),
    ]
