# Generated by Django 4.2.8 on 2024-05-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_remove_historicalrgbview_b_scale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrgbrendercontext",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="The description of the view",
                max_length=8000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rgbrendercontext",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="The description of the view",
                max_length=8000,
                null=True,
            ),
        ),
    ]
