# Generated by Django 4.2.8 on 2024-05-28 11:08

import core.enums
from django.db import migrations, models
import django.db.models.deletion
import django_choices_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_historicalrgbrendercontext_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrgbrendercontext",
            name="blending",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("additive", "Additive"),
                    ("multiplicative", "Multiplicative"),
                ],
                choices_enum=core.enums.BlendingChoices,
                default="additive",
                help_text="The blending of the channel",
                max_length=14,
            ),
        ),
        migrations.AddField(
            model_name="rgbrendercontext",
            name="blending",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("additive", "Additive"),
                    ("multiplicative", "Multiplicative"),
                ],
                choices_enum=core.enums.BlendingChoices,
                default="additive",
                help_text="The blending of the channel",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="rgbview",
            name="context",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="core.rgbrendercontext",
            ),
        ),
    ]
