# Generated by Django 6.0.6 on 2026-07-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_replace_feature_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='axis',
            name='description',
            field=models.CharField(blank=True, help_text="A free-form description of what the axis measures, e.g. 'distance from the coverslip'", max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tablecolumn',
            name='description',
            field=models.CharField(blank=True, help_text="A free-form description of what the column holds, e.g. 'mean GFP intensity within the segmented object'", max_length=1000, null=True),
        ),
    ]
