# Generated by Django 6.0.6 on 2026-07-15 18:20
#
# Drops the stored `kind` column: a coordinate system's kind is a pure function of
# which ownership FK is set (see CoordinateSystem.kind), so the column was a second,
# unconstrained copy of a fact the cascade already enforces -- free to drift, never
# consulted anywhere an FK check wasn't strictly more correct. No data migration:
# nothing is derived FROM the old labels, they are simply discarded.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_axis_description_tablecolumn_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinatesystem',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='historicalcoordinatesystem',
            name='kind',
        ),
        migrations.AlterField(
            model_name='coordinatesystem',
            name='epoch',
            field=models.DateTimeField(blank=True, help_text="The wall-clock instant this system's time axis has its origin at, so that `wall_clock = epoch + t * unit`. A property of the *space*, not of any composition over it -- two scenes sharing one space cannot disagree about when its clock starts. Meaningful only for a calibrated system with a TIME axis (a scene's world, a shared hub); optional even there: an unanchored clock is still a perfectly composable relative coordinate", null=True),
        ),
        migrations.AlterField(
            model_name='coordinatesystem',
            name='scene',
            field=models.OneToOneField(blank=True, help_text='The scene whose world space this is', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_coordinate_system', to='core.scene'),
        ),
        migrations.AlterField(
            model_name='historicalcoordinatesystem',
            name='epoch',
            field=models.DateTimeField(blank=True, help_text="The wall-clock instant this system's time axis has its origin at, so that `wall_clock = epoch + t * unit`. A property of the *space*, not of any composition over it -- two scenes sharing one space cannot disagree about when its clock starts. Meaningful only for a calibrated system with a TIME axis (a scene's world, a shared hub); optional even there: an unanchored clock is still a perfectly composable relative coordinate", null=True),
        ),
        migrations.AlterField(
            model_name='historicalcoordinatesystem',
            name='scene',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The scene whose world space this is', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.scene'),
        ),
    ]
