# Generated by Django 4.2.8 on 2024-05-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_historicalrgbrendercontext_blending_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrgbview",
            name="rescale",
            field=models.BooleanField(
                default=False, help_text="Whether the channel should be rescaled"
            ),
        ),
        migrations.AddField(
            model_name="rgbview",
            name="rescale",
            field=models.BooleanField(
                default=False, help_text="Whether the channel should be rescaled"
            ),
        ),
    ]
