# Generated by Django 4.2.8 on 2024-10-28 11:13

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_derivedview_remove_image_file_origins_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelAccessor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keys",
                    models.JSONField(
                        help_text="The key of the column", max_length=1000
                    ),
                ),
                (
                    "min_index",
                    models.IntegerField(
                        blank=True,
                        help_text="The index of the row where this view starts (null if all rows)",
                        null=True,
                    ),
                ),
                (
                    "max_index",
                    models.IntegerField(
                        blank=True,
                        help_text="The index of the row where this view ends (null if all rows)",
                        null=True,
                    ),
                ),
                (
                    "is_global",
                    models.BooleanField(
                        default=False, help_text="Whether the view is global or not"
                    ),
                ),
                (
                    "pixel_view",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_accessors",
                        to="core.pixelview",
                    ),
                ),
                (
                    "table",
                    simple_history.models.HistoricForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.table"
                    ),
                ),
            ],
            options={
                "default_related_name": "label_accessors",
            },
        ),
        migrations.CreateModel(
            name="ImageAccessor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keys",
                    models.JSONField(
                        help_text="The key of the column", max_length=1000
                    ),
                ),
                (
                    "min_index",
                    models.IntegerField(
                        blank=True,
                        help_text="The index of the row where this view starts (null if all rows)",
                        null=True,
                    ),
                ),
                (
                    "max_index",
                    models.IntegerField(
                        blank=True,
                        help_text="The index of the row where this view ends (null if all rows)",
                        null=True,
                    ),
                ),
                (
                    "is_global",
                    models.BooleanField(
                        default=False, help_text="Whether the view is global or not"
                    ),
                ),
                (
                    "table",
                    simple_history.models.HistoricForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.table"
                    ),
                ),
            ],
            options={
                "default_related_name": "image_accessors",
            },
        ),
    ]
