# Generated by Django 4.2.8 on 2024-05-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_historicalrgbview_rescale_rgbview_rescale"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrgbview",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Whether the viewis active"
            ),
        ),
        migrations.AddField(
            model_name="rgbview",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Whether the viewis active"
            ),
        ),
    ]
