# Generated by Django 6.0.6 on 2026-07-15 19:17
#
# Scenes now carry `world` -- WHICH space they compose over -- as a first-class,
# always-set FK, distinct from CoordinateSystem.scene (ownership of a *minted*
# world, which keeps cascading with its scene). The backfill points every existing
# scene at the world it already owned; from here on a scene may instead adopt an
# ownerless hub, so the FK is RESTRICT: a space is never deleted out from under a
# scene, and a minted world's cascade-on-scene-delete still resolves because the
# restricting scene is in the same deletion set.

import django.db.models.deletion
from django.db import migrations, models


def backfill_world(apps, schema_editor):
    """Point each scene at the world it owns; mint one for any scene without.

    The mint branch is defensive only: the API has never produced a scene without
    an owned world, but the NOT NULL alter below must not be able to fail.
    """
    Scene = apps.get_model("core", "Scene")
    CoordinateSystem = apps.get_model("core", "CoordinateSystem")

    for system in CoordinateSystem.objects.filter(scene__isnull=False).only("pk", "scene_id"):
        Scene.objects.filter(pk=system.scene_id).update(world=system.pk)

    for scene in Scene.objects.filter(world__isnull=True).only("pk", "name", "organization_id"):
        system = CoordinateSystem.objects.create(
            name=f"{scene.name}/world",
            scene_id=scene.pk,
            organization_id=scene.organization_id,
        )
        Scene.objects.filter(pk=scene.pk).update(world=system.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_kind_is_derived_from_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscene',
            name='world',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The shared space this scene composes its layers over: either a world minted for this scene (which also carries CoordinateSystem.scene and cascades with it) or an adopted ownerless hub, which many scenes can share and which outlives each of them', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='scene',
            name='world',
            field=models.ForeignKey(help_text='The shared space this scene composes its layers over: either a world minted for this scene (which also carries CoordinateSystem.scene and cascades with it) or an adopted ownerless hub, which many scenes can share and which outlives each of them', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='scenes', to='core.coordinatesystem'),
        ),
        migrations.RunPython(backfill_world, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='scene',
            name='world',
            field=models.ForeignKey(help_text='The shared space this scene composes its layers over: either a world minted for this scene (which also carries CoordinateSystem.scene and cascades with it) or an adopted ownerless hub, which many scenes can share and which outlives each of them', on_delete=django.db.models.deletion.RESTRICT, related_name='scenes', to='core.coordinatesystem'),
        ),
    ]
