# Generated by Django 4.2.8 on 2024-05-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_historicalrgbview_active_rgbview_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalrgbview",
            name="context",
        ),
        migrations.RemoveField(
            model_name="rgbview",
            name="context",
        ),
        migrations.AddField(
            model_name="rgbview",
            name="contexts",
            field=models.ManyToManyField(
                related_name="views", to="core.rgbrendercontext"
            ),
        ),
    ]
