# Generated by Django 4.2.8 on 2024-10-28 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_labelaccessor_imageaccessor"),
    ]

    operations = [
        migrations.AddField(
            model_name="derivedview",
            name="operation",
            field=models.CharField(
                help_text="The operation that was used to create the image",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalderivedview",
            name="operation",
            field=models.CharField(
                help_text="The operation that was used to create the image",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="derivedview",
            name="origin_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="derived_from_views",
                to="core.image",
            ),
        ),
    ]
