# Generated by Django 6.0.6 on 2026-07-16 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_rfc6_registration_grafts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscene',
            name='world',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="The space this scene composes its layers over: a world minted for this scene (which also carries CoordinateSystem.scene and cascades with it) or an adopted existing system -- a hub, a dataset's intrinsic grid, a calibration, a collection's space -- which many scenes can share and which outlives each of them. RESTRICT: while a scene is rooted in a space, neither the space nor its owning container can be deleted", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.coordinatesystem'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='world',
            field=models.ForeignKey(help_text="The space this scene composes its layers over: a world minted for this scene (which also carries CoordinateSystem.scene and cascades with it) or an adopted existing system -- a hub, a dataset's intrinsic grid, a calibration, a collection's space -- which many scenes can share and which outlives each of them. RESTRICT: while a scene is rooted in a space, neither the space nor its owning container can be deleted", on_delete=django.db.models.deletion.RESTRICT, related_name='scenes', to='core.coordinatesystem'),
        ),
    ]
