# Generated by Django 4.2.8 on 2024-05-29 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_rename_governed_by_historicalrgbrendercontext_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrgbrendercontext",
            name="thumbnail",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The store of the thumbnail",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.mediastore",
            ),
        ),
        migrations.AddField(
            model_name="rgbrendercontext",
            name="thumbnail",
            field=models.ForeignKey(
                blank=True,
                help_text="The store of the thumbnail",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.mediastore",
            ),
        ),
        migrations.CreateModel(
            name="RenderTree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tree", models.JSONField()),
                (
                    "linked_contexts",
                    models.ManyToManyField(
                        related_name="linked_trees", to="core.rgbrendercontext"
                    ),
                ),
            ],
        ),
    ]
