# Generated by Django 6.0.6 on 2026-07-16 11:19

import core.enums
import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_scene_world_help_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineagelink',
            name='source_lens',
        ),
        migrations.RemoveField(
            model_name='lineagelink',
            name='source_mask',
        ),
        migrations.RemoveField(
            model_name='lineagelink',
            name='target_lens',
        ),
        migrations.AddField(
            model_name='historicaltransformation',
            name='value_relation',
            field=django_choices_field.fields.TextChoicesField(blank=True, choices=[('IDENTICAL', "Identical (the source's numbers)"), ('TRANSFORMED', 'Transformed (same quantity, new numbers)'), ('CATEGORIZED', 'Categorized (values became labels)')], choices_enum=core.enums.ValueRelationChoices, help_text='What the derivation this edge records did to the *values* -- the axis the spatial kind says nothing about: a threshold is spatially IDENTITY with CATEGORIZED values, a crop is value-IDENTICAL, a deconvolution TRANSFORMED. One derivation event, one row, two orthogonal statements -- never a parallel table. Null means unstated. Meaningful only on a derivation (cross-container fact) edge: a registration relates spaces, and values do not cross it', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='transformation',
            name='value_relation',
            field=django_choices_field.fields.TextChoicesField(blank=True, choices=[('IDENTICAL', "Identical (the source's numbers)"), ('TRANSFORMED', 'Transformed (same quantity, new numbers)'), ('CATEGORIZED', 'Categorized (values became labels)')], choices_enum=core.enums.ValueRelationChoices, help_text='What the derivation this edge records did to the *values* -- the axis the spatial kind says nothing about: a threshold is spatially IDENTITY with CATEGORIZED values, a crop is value-IDENTICAL, a deconvolution TRANSFORMED. One derivation event, one row, two orthogonal statements -- never a parallel table. Null means unstated. Meaningful only on a derivation (cross-container fact) edge: a registration relates spaces, and values do not cross it', max_length=11, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalLineageLink',
        ),
        migrations.DeleteModel(
            name='LineageLink',
        ),
    ]
