# Generated by Django 4.2.8 on 2024-05-29 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_historicalrgbrendercontext_thumbnail_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalrgbrendercontext",
            name="thumbnail",
        ),
        migrations.RemoveField(
            model_name="rgbrendercontext",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="historicalsnapshot",
            name="context",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The context of the snapshot",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.rgbrendercontext",
            ),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="context",
            field=models.ForeignKey(
                blank=True,
                help_text="The context of the snapshot",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.rgbrendercontext",
            ),
        ),
    ]
