# Generated by Django 6.0.6 on 2026-07-16 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_value_relations_replace_lineage_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallayer',
            name='mesh',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='mesh',
        ),
        migrations.RemoveField(
            model_name='omeplanemetadata',
            name='anchor',
        ),
        migrations.RemoveField(
            model_name='historicallayer',
            name='coordinate_system',
        ),
        migrations.RemoveField(
            model_name='historicallayer',
            name='id_column',
        ),
        migrations.RemoveField(
            model_name='historicallayer',
            name='t_column',
        ),
        migrations.RemoveField(
            model_name='historicallayer',
            name='table',
        ),
        migrations.RemoveField(
            model_name='historicallayer',
            name='track_id_column',
        ),
        migrations.RemoveField(
            model_name='historicallayer',
            name='x_column',
        ),
        migrations.RemoveField(
            model_name='historicallayer',
            name='y_column',
        ),
        migrations.RemoveField(
            model_name='historicallayer',
            name='z_column',
        ),
        migrations.RemoveField(
            model_name='historicalscene',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='coordinate_system',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='id_column',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='t_column',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='table',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='track_id_column',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='x_column',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='y_column',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='z_column',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='parent',
        ),
        migrations.AlterField(
            model_name='historicallayer',
            name='table_dataset',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='(point/track) The table dataset whose declared coordinate columns provide the coordinates; its own coordinate system is the space, and its column roles are the mapping -- nothing is duplicated per layer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.tabledataset'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='table_dataset',
            field=models.ForeignKey(blank=True, help_text='(point/track) The table dataset whose declared coordinate columns provide the coordinates; its own coordinate system is the space, and its column roles are the mapping -- nothing is duplicated per layer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='core.tabledataset'),
        ),
        migrations.DeleteModel(
            name='Mesh',
        ),
        migrations.DeleteModel(
            name='OmePlaneMetadata',
        ),
    ]
