# Generated by Django 6.0.6 on 2026-07-17 08:51

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('core', '0029_vestigial_sweep'),
        ('datalayer', '0001_initial'),
        ('koherent', '0003_rename_assignation_to_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='The name of the snapshot', max_length=1000)),
                ('major_color', models.JSONField(blank=True, help_text='The dominant color of the image, for tinting a placeholder while it loads', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time the snapshot was taken')),
                ('created_through', models.ForeignKey(blank=True, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to='koherent.task')),
                ('created_through_by', models.ForeignKey(blank=True, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, help_text='The user that took the snapshot', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization the snapshot belongs to', on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization')),
                ('pinned_by', models.ManyToManyField(blank=True, help_text='The users that have pinned the snapshot', related_name='pinned_scene_snapshots', to=settings.AUTH_USER_MODEL)),
                ('scene', models.ForeignKey(help_text='The composition this is a picture of', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.scene')),
                ('store', models.ForeignKey(help_text='The media store holding the rendered image', on_delete=django.db.models.deletion.CASCADE, related_name='scene_snapshots', to='datalayer.mediastore')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalSceneSnapshot',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='The name of the snapshot', max_length=1000)),
                ('major_color', models.JSONField(blank=True, help_text='The dominant color of the image, for tinting a placeholder while it loads', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='The time the snapshot was taken')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client')),
                ('created_through', models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task')),
                ('created_through_by', models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, help_text='The user that took the snapshot', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, help_text='The organization the snapshot belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization')),
                ('scene', models.ForeignKey(blank=True, db_constraint=False, help_text='The composition this is a picture of', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.scene')),
                ('store', models.ForeignKey(blank=True, db_constraint=False, help_text='The media store holding the rendered image', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datalayer.mediastore')),
                ('task', models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.scenesnapshot')),
            ],
            options={
                'verbose_name': 'historical scene snapshot',
                'verbose_name_plural': 'historical scene snapshots',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
