# Generated by Django 4.2.8 on 2024-05-29 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_remove_historicalrgbrendercontext_thumbnail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rendertree",
            name="name",
            field=models.CharField(
                default="", help_text="The name of the tree", max_length=1000
            ),
        ),
        migrations.AlterField(
            model_name="snapshot",
            name="context",
            field=models.ForeignKey(
                blank=True,
                help_text="The context of the snapshot",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="snapshots",
                to="core.rgbrendercontext",
            ),
        ),
    ]
