# Generated by Django 6.0.6 on 2026-07-17 09:41

import core.enums
import django.db.models.deletion
import django_choices_field.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('core', '0030_scenesnapshot_historicalscenesnapshot'),
        ('koherent', '0003_rename_assignation_to_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscene',
            name='background_color',
            field=models.JSONField(blank=True, help_text='The viewer background, as RGBA. Null to let the viewer use its own', null=True),
        ),
        migrations.AddField(
            model_name='historicalscene',
            name='preferred_view',
            field=django_choices_field.fields.TextChoicesField(choices=[('two_d', '2D'), ('three_d', '3D'), ('auto', 'Auto')], choices_enum=core.enums.PreferredViewChoices, default='auto', help_text='How a viewer should open this scene: flat, volumetric, or its own choice. Defaults to AUTO -- a scene nobody has expressed a preference for should not claim one', max_length=7),
        ),
        migrations.AddField(
            model_name='scene',
            name='background_color',
            field=models.JSONField(blank=True, help_text='The viewer background, as RGBA. Null to let the viewer use its own', null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='preferred_view',
            field=django_choices_field.fields.TextChoicesField(choices=[('two_d', '2D'), ('three_d', '3D'), ('auto', 'Auto')], choices_enum=core.enums.PreferredViewChoices, default='auto', help_text='How a viewer should open this scene: flat, volumetric, or its own choice. Defaults to AUTO -- a scene nobody has expressed a preference for should not claim one', max_length=7),
        ),
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the tour, e.g. 'overview' or 'dive to the mitochondria'", max_length=255)),
                ('description', models.CharField(blank=True, help_text='What the tour shows', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time the tour was created')),
                ('created_through', models.ForeignKey(blank=True, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to='koherent.task')),
                ('created_through_by', models.ForeignKey(blank=True, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, help_text='The user that created the tour', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization the tour belongs to', on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization')),
                ('scene', models.ForeignKey(help_text='The scene this tour flies through', on_delete=django.db.models.deletion.CASCADE, related_name='animations', to='core.scene')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAnimation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the tour, e.g. 'overview' or 'dive to the mitochondria'", max_length=255)),
                ('description', models.CharField(blank=True, help_text='What the tour shows', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='The time the tour was created')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client')),
                ('created_through', models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task')),
                ('created_through_by', models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, help_text='The user that created the tour', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.animation')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, help_text='The organization the tour belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization')),
                ('scene', models.ForeignKey(blank=True, db_constraint=False, help_text='The scene this tour flies through', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.scene')),
                ('task', models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task')),
            ],
            options={
                'verbose_name': 'historical animation',
                'verbose_name_plural': 'historical animations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AnimationWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text="The pose's index in the tour. Written by enumeration from the authored list, never supplied by a caller")),
                ('name', models.CharField(blank=True, default='', help_text="What this stop shows, e.g. 'the nucleus'", max_length=255)),
                ('camera', models.JSONField(help_text="Where the camera is, as a CameraState: a position keyed by the world's axis names, plus the flat and volumetric views of it")),
                ('duration_ms', models.PositiveIntegerField(default=1000, help_text='How long the viewer takes to travel TO this pose, in milliseconds. Ignored for the first pose, which is where the tour starts')),
                ('easing', django_choices_field.fields.TextChoicesField(choices=[('linear', 'Linear'), ('ease_in', 'Ease in'), ('ease_out', 'Ease out'), ('ease_in_out', 'Ease in-out')], choices_enum=core.enums.EasingChoices, default='ease_in_out', help_text='How the viewer eases the camera along that travel', max_length=11)),
                ('animation', models.ForeignKey(help_text='The tour this pose belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='core.animation')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('animation', 'order'), name='unique_animation_waypoint_order')],
            },
        ),
    ]
