# Generated by Django 4.2.8 on 2024-06-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_roigroup_historicalroigroup_roi_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrgbrendercontext",
            name="c",
            field=models.IntegerField(
                default=0, help_text="The index of the c (if not in multi-channel mode)"
            ),
        ),
        migrations.AddField(
            model_name="historicalrgbrendercontext",
            name="t",
            field=models.IntegerField(
                default=0, help_text="The index of the t (if not in hypermode)"
            ),
        ),
        migrations.AddField(
            model_name="historicalrgbrendercontext",
            name="z",
            field=models.IntegerField(
                default=0, help_text="The index of the z (if not in 3D mode)"
            ),
        ),
        migrations.AddField(
            model_name="rgbrendercontext",
            name="c",
            field=models.IntegerField(
                default=0, help_text="The index of the c (if not in multi-channel mode)"
            ),
        ),
        migrations.AddField(
            model_name="rgbrendercontext",
            name="t",
            field=models.IntegerField(
                default=0, help_text="The index of the t (if not in hypermode)"
            ),
        ),
        migrations.AddField(
            model_name="rgbrendercontext",
            name="z",
            field=models.IntegerField(
                default=0, help_text="The index of the z (if not in 3D mode)"
            ),
        ),
    ]
