# Generated by Django 6.0.6 on 2026-07-17 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_field_transformations'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablecolumn',
            name='references',
            field=models.ForeignKey(blank=True, help_text="The table whose rows this column's values identify. Its declared schema says which column carries that identity (its single INDEX coordinate column); this FK states only *which table*, and the rest is derived. Only a data column (never a COORDINATE) may reference", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referenced_by', to='core.tabledataset'),
        ),
    ]
