# Generated by Django 6.0.6 on 2026-07-22 17:48

import core.enums
import django.db.models.deletion
import django_choices_field.fields
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


def _purge_shape_layers(apps, schema_editor):
    # Dev data is disposable (agreed): DataRoi rows die with their table below,
    # and the SHAPE layers that pointed at them would otherwise survive as
    # orphaned rows under the retargeted 'annotation' kind vocabulary. Raw SQL,
    # not the ORM: django_choices_field validates 'shape' against the *current*
    # enum, which no longer has it.
    schema_editor.execute("DELETE FROM core_historicallayer WHERE kind = 'shape'")
    schema_editor.execute("DELETE FROM core_layer WHERE kind = 'shape'")


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('core', '0034_spec_is_stored'),
        ('koherent', '0003_rename_assignation_to_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_purge_shape_layers, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='layer',
            name='data_roi',
        ),
        migrations.RemoveField(
            model_name='historicaldataroi',
            name='history_relation',
        ),
        migrations.RemoveField(
            model_name='historicallayer',
            name='data_roi',
        ),
        migrations.RemoveField(
            model_name='historicaldataroi',
            name='client',
        ),
        migrations.RemoveField(
            model_name='historicaldataroi',
            name='coordinate_system',
        ),
        migrations.RemoveField(
            model_name='historicaldataroi',
            name='created_through',
        ),
        migrations.RemoveField(
            model_name='historicaldataroi',
            name='created_through_by',
        ),
        migrations.RemoveField(
            model_name='historicaldataroi',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='historicaldataroi',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldataroi',
            name='task',
        ),
        migrations.RemoveField(
            model_name='historicallayer',
            name='fill_color',
        ),
        migrations.RemoveField(
            model_name='historicallayer',
            name='filled',
        ),
        migrations.RemoveField(
            model_name='historicallayer',
            name='stroke_color',
        ),
        migrations.RemoveField(
            model_name='historicallayer',
            name='stroke_width',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='fill_color',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='filled',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='stroke_color',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='stroke_width',
        ),
        migrations.AlterField(
            model_name='historicallayer',
            name='kind',
            field=django_choices_field.fields.TextChoicesField(choices=[('image', 'Image (array data)'), ('annotation', 'Annotation (drawn geometry)'), ('point', 'Point (tabular point cloud)'), ('track', 'Track (tabular trajectories)'), ('mesh', 'Mesh (3D surface)')], choices_enum=core.enums.LayerKindChoices, default='image', help_text='The kind of layer, discriminating its data source and render settings', max_length=10),
        ),
        migrations.AlterField(
            model_name='layer',
            name='kind',
            field=django_choices_field.fields.TextChoicesField(choices=[('image', 'Image (array data)'), ('annotation', 'Annotation (drawn geometry)'), ('point', 'Point (tabular point cloud)'), ('track', 'Track (tabular trajectories)'), ('mesh', 'Mesh (3D surface)')], choices_enum=core.enums.LayerKindChoices, default='image', help_text='The kind of layer, discriminating its data source and render settings', max_length=10),
        ),
        migrations.CreateModel(
            name='AnnotationCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this annotation collection', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A free-form description of this annotation collection', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this annotation collection was created')),
                ('created_through', models.ForeignKey(blank=True, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to='koherent.task')),
                ('created_through_by', models.ForeignKey(blank=True, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, help_text='The user that created this annotation collection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotation_collections', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization this annotation collection belongs to', on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization')),
                ('scene', models.OneToOneField(blank=True, help_text='The scene this collection was minted for as its default drawing surface, if any. One per scene; bookkeeping only, placement is the registration edge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotation_collection', to='core.scene')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('kind', django_choices_field.fields.TextChoicesField(choices=[('ellipse', 'Ellipse'), ('polygon', 'POLYGON'), ('line', 'Line'), ('rectangle', 'Rectangle (XY)'), ('spectral_rectangle', 'Spectral Rectangle (XYC)'), ('temporal_rectangle', 'Temporal Rectangle (XYT)'), ('cube', 'Cube (XYZ)'), ('spectral_cube', 'Spectral Cube (XYZC)'), ('temporal_cube', 'Temporal Cube (XYZT)'), ('hypercube', 'Hypercube (XYZT)'), ('spectral_hypercube', 'Spectral Hypercube (XYZTC)'), ('path', 'Path'), ('unknown', 'Unknown'), ('frame', 'Frame'), ('slice', 'Slice'), ('point', 'Point')], choices_enum=core.enums.RoiKindChoices, default='path', help_text='The geometric kind of the annotation (rectangle, polygon, path, ...), which fixes how its vectors are read', max_length=18)),
                ('selectors', models.JSONField(default=dict, help_text="The discrete coordinates this annotation is pinned to, keyed by axis name, e.g. {'t': 0, 'c': 0}. An axis the annotation does not pin is one it spans")),
                ('vectors', models.JSONField(default=list, help_text="A list of the annotation's vectors (specific for each kind), in the collection's coordinate system's own units")),
                ('intrinsic_bbox', models.JSONField(blank=True, help_text="The annotation's axis-aligned bounding box in the nearest intrinsic space, as {'min': [...], 'max': [...]}. Derived from all corners of the geometry, never from min/max alone", null=True)),
                ('created_with_transforms', models.PositiveIntegerField(default=0, help_text='The version of the transformation chain this annotation was authored against. Provenance only: it is never used to resolve a coordinate')),
                ('stroke_color', models.JSONField(blank=True, default=None, help_text='The stroke (outline) color of the geometry (RGBA)', null=True)),
                ('fill_color', models.JSONField(blank=True, default=None, help_text='The fill color of the geometry (RGBA), or null for no fill', null=True)),
                ('stroke_width', models.FloatField(default=1.0, help_text="The stroke width of the geometry, in the drawing space's units")),
                ('filled', models.BooleanField(default=False, help_text='Whether the geometry is filled with fill_color')),
                ('created_through', models.ForeignKey(blank=True, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to='koherent.task')),
                ('created_through_by', models.ForeignKey(blank=True, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, help_text='The user that drew this annotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(help_text="The collection this annotation belongs to; its geometry is expressed in the collection's own coordinate system", on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='core.annotationcollection')),
            ],
        ),
        migrations.AddField(
            model_name='coordinatesystem',
            name='annotation_collection',
            field=models.OneToOneField(blank=True, help_text='The annotation collection whose drawing space this is', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinate_system', to='core.annotationcollection'),
        ),
        migrations.AddField(
            model_name='historicalcoordinatesystem',
            name='annotation_collection',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The annotation collection whose drawing space this is', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.annotationcollection'),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='annotation_collection',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='(annotation) The annotation collection, owning its own coordinate system, whose drawn shapes this layer renders', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.annotationcollection'),
        ),
        migrations.AddField(
            model_name='layer',
            name='annotation_collection',
            field=models.ForeignKey(blank=True, help_text='(annotation) The annotation collection, owning its own coordinate system, whose drawn shapes this layer renders', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='core.annotationcollection'),
        ),
        migrations.CreateModel(
            name='HistoricalAnnotation',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('kind', django_choices_field.fields.TextChoicesField(choices=[('ellipse', 'Ellipse'), ('polygon', 'POLYGON'), ('line', 'Line'), ('rectangle', 'Rectangle (XY)'), ('spectral_rectangle', 'Spectral Rectangle (XYC)'), ('temporal_rectangle', 'Temporal Rectangle (XYT)'), ('cube', 'Cube (XYZ)'), ('spectral_cube', 'Spectral Cube (XYZC)'), ('temporal_cube', 'Temporal Cube (XYZT)'), ('hypercube', 'Hypercube (XYZT)'), ('spectral_hypercube', 'Spectral Hypercube (XYZTC)'), ('path', 'Path'), ('unknown', 'Unknown'), ('frame', 'Frame'), ('slice', 'Slice'), ('point', 'Point')], choices_enum=core.enums.RoiKindChoices, default='path', help_text='The geometric kind of the annotation (rectangle, polygon, path, ...), which fixes how its vectors are read', max_length=18)),
                ('selectors', models.JSONField(default=dict, help_text="The discrete coordinates this annotation is pinned to, keyed by axis name, e.g. {'t': 0, 'c': 0}. An axis the annotation does not pin is one it spans")),
                ('vectors', models.JSONField(default=list, help_text="A list of the annotation's vectors (specific for each kind), in the collection's coordinate system's own units")),
                ('intrinsic_bbox', models.JSONField(blank=True, help_text="The annotation's axis-aligned bounding box in the nearest intrinsic space, as {'min': [...], 'max': [...]}. Derived from all corners of the geometry, never from min/max alone", null=True)),
                ('created_with_transforms', models.PositiveIntegerField(default=0, help_text='The version of the transformation chain this annotation was authored against. Provenance only: it is never used to resolve a coordinate')),
                ('stroke_color', models.JSONField(blank=True, default=None, help_text='The stroke (outline) color of the geometry (RGBA)', null=True)),
                ('fill_color', models.JSONField(blank=True, default=None, help_text='The fill color of the geometry (RGBA), or null for no fill', null=True)),
                ('stroke_width', models.FloatField(default=1.0, help_text="The stroke width of the geometry, in the drawing space's units")),
                ('filled', models.BooleanField(default=False, help_text='Whether the geometry is filled with fill_color')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client')),
                ('collection', models.ForeignKey(blank=True, db_constraint=False, help_text="The collection this annotation belongs to; its geometry is expressed in the collection's own coordinate system", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.annotationcollection')),
                ('created_through', models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task')),
                ('created_through_by', models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, help_text='The user that drew this annotation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.annotation')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task')),
            ],
            options={
                'verbose_name': 'historical annotation',
                'verbose_name_plural': 'historical annotations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAnnotationCollection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this annotation collection', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A free-form description of this annotation collection', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='The time this annotation collection was created')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client')),
                ('created_through', models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task')),
                ('created_through_by', models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, help_text='The user that created this annotation collection', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.annotationcollection')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, help_text='The organization this annotation collection belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization')),
                ('scene', models.ForeignKey(blank=True, db_constraint=False, help_text='The scene this collection was minted for as its default drawing surface, if any. One per scene; bookkeeping only, placement is the registration edge', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.scene')),
                ('task', models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task')),
            ],
            options={
                'verbose_name': 'historical annotation collection',
                'verbose_name_plural': 'historical annotation collections',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='DataRoi',
        ),
        migrations.DeleteModel(
            name='HistoricalDataRoi',
        ),
    ]
