# Generated by Django 6.0.6 on 2026-07-22 19:41

import core.fields
import django.contrib.postgres.indexes
from django.conf import settings
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_annotations'),
        ('koherent', '0003_rename_assignation_to_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # The cube contrib extension (bundled in the daten images): an axis-aligned
        # N-D box with a GiST opclass, powering the &&/@>/<-> annotation search.
        CreateExtension("cube"),
        # A rename, not remove+add: the pinned dict keeps its data. The generated
        # remove/add pairs were hand-converted; the historical mirror renames too.
        migrations.RenameField(
            model_name='annotation',
            old_name='selectors',
            new_name='coordinates',
        ),
        migrations.RenameField(
            model_name='historicalannotation',
            old_name='selectors',
            new_name='coordinates',
        ),
        migrations.AlterField(
            model_name='annotation',
            name='coordinates',
            field=models.JSONField(default=dict, help_text="The discrete coordinates this annotation is pinned to, keyed by coordinate name, e.g. {'t': 0, 'c': 0}. A coordinate the annotation does not pin is one it spans"),
        ),
        migrations.AlterField(
            model_name='historicalannotation',
            name='coordinates',
            field=models.JSONField(default=dict, help_text="The discrete coordinates this annotation is pinned to, keyed by coordinate name, e.g. {'t': 0, 'c': 0}. A coordinate the annotation does not pin is one it spans"),
        ),
        migrations.AddField(
            model_name='annotation',
            name='bbox_cube',
            field=core.fields.CubeField(blank=True, editable=False, help_text='The intrinsic bounding box as a Postgres cube, denormalized from intrinsic_bbox at write time for GiST-indexed overlap/containment/nearest search. Write-only: the API reads intrinsic_bbox', null=True),
        ),
        # The historical table gets the cube column too (unindexed) -- history rows
        # mirror the concrete row's columns, and an unindexed cube is harmless.
        migrations.AddField(
            model_name='historicalannotation',
            name='bbox_cube',
            field=core.fields.CubeField(blank=True, editable=False, help_text='The intrinsic bounding box as a Postgres cube, denormalized from intrinsic_bbox at write time for GiST-indexed overlap/containment/nearest search. Write-only: the API reads intrinsic_bbox', null=True),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=django.contrib.postgres.indexes.GinIndex(fields=['coordinates'], name='annotation_coords_gin'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=django.contrib.postgres.indexes.GistIndex(fields=['bbox_cube'], name='annotation_bbox_gist'),
        ),
    ]
