# Generated by Django 6.0.6 on 2026-07-23 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('core', '0036_annotation_spatial'),
        ('datalayer', '0001_initial'),
        ('koherent', '0003_rename_assignation_to_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scenesnapshot',
            index=models.Index(fields=['scene', '-created_at'], name='scene_snapshot_latest_idx'),
        ),
    ]
