# Generated by Django 6.0.6 on 2026-07-24 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_scenesnapshot_scene_snapshot_latest_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinatesystem',
            name='scene',
        ),
        migrations.RemoveField(
            model_name='historicalcoordinatesystem',
            name='scene',
        ),
        migrations.AlterField(
            model_name='coordinatesystem',
            name='epoch',
            field=models.DateTimeField(blank=True, help_text="The wall-clock instant this system's time axis has its origin at, so that `wall_clock = epoch + t * unit`. A property of the *space*, not of any composition over it -- two scenes sharing one space cannot disagree about when its clock starts. Meaningful only for a calibrated system with a TIME axis (a shared world space); optional even there: an unanchored clock is still a perfectly composable relative coordinate", null=True),
        ),
        migrations.AlterField(
            model_name='historicalcoordinatesystem',
            name='epoch',
            field=models.DateTimeField(blank=True, help_text="The wall-clock instant this system's time axis has its origin at, so that `wall_clock = epoch + t * unit`. A property of the *space*, not of any composition over it -- two scenes sharing one space cannot disagree about when its clock starts. Meaningful only for a calibrated system with a TIME axis (a shared world space); optional even there: an unanchored clock is still a perfectly composable relative coordinate", null=True),
        ),
        migrations.AlterField(
            model_name='historicalscene',
            name='world',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="The space this scene composes its layers over: a shared world system created for convenience alongside the scene, or an adopted existing system -- a shared space, a dataset's intrinsic grid, a calibration, a collection's space. Never owned by the scene: many scenes can share it, it outlives each of them, and deleting a scene never deletes it. RESTRICT: while a scene is rooted in a space, neither the space nor its owning container can be deleted", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.coordinatesystem'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='world',
            field=models.ForeignKey(help_text="The space this scene composes its layers over: a shared world system created for convenience alongside the scene, or an adopted existing system -- a shared space, a dataset's intrinsic grid, a calibration, a collection's space. Never owned by the scene: many scenes can share it, it outlives each of them, and deleting a scene never deletes it. RESTRICT: while a scene is rooted in a space, neither the space nor its owning container can be deleted", on_delete=django.db.models.deletion.RESTRICT, related_name='scenes', to='core.coordinatesystem'),
        ),
    ]
