# Generated by Django 6.0.6 on 2026-07-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_coordinatesystem_scene_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axis',
            name='unit',
            field=models.CharField(blank=True, help_text="The physical unit of the axis, e.g. 'micrometer'. A pint unit (the kanne `Unit` scalar), validated on write; 'a.u.' for arbitrary units. Set on calibrated (PHYSICAL/SHARED) axes, always null on pixel (INTRINSIC/ARRAY) axes", max_length=64, null=True),
        ),
    ]
