# Generated by Django 6.0.6 on 2026-07-26 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_annotation_boxes_name_their_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='adataset',
            name='coordinate_system',
            field=models.ForeignKey(blank=True, help_text="The coordinate system this dataset's pixels are expressed in: its level-0 grid. PROTECT, because a space cannot be deleted while data lives in it", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='annotationcollection',
            name='coordinate_system',
            field=models.ForeignKey(blank=True, help_text="The coordinate system this collection's shapes are drawn in. All its annotations share it, so they share one placement story: the collection is related to other spaces by edges, the shapes just have vectors", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annotation_collections', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='dataarray',
            name='coordinate_system',
            field=models.ForeignKey(blank=True, help_text="The coordinate system this level's voxels are expressed in. Level 0 shares its dataset's; every downsampled level has its own, with a stored edge relating the two", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_arrays', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='historicaladataset',
            name='coordinate_system',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="The coordinate system this dataset's pixels are expressed in: its level-0 grid. PROTECT, because a space cannot be deleted while data lives in it", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='historicalannotationcollection',
            name='coordinate_system',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="The coordinate system this collection's shapes are drawn in. All its annotations share it, so they share one placement story: the collection is related to other spaces by edges, the shapes just have vectors", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='historicallens',
            name='coordinate_system',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="The coordinate system this lens' voxels are expressed in. An unsliced lens shares its dataset's; a sliced one has its own, with a stored edge carrying the shift", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='historicalmeshcollection',
            name='coordinate_system',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="The coordinate system this collection's vertices are expressed in. An edge relates it to whatever the meshes were extracted from -- an identity when the grids agree, a scale when they do not", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='historicaltabledataset',
            name='coordinate_system',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="The coordinate system this table's coordinate columns are expressed in. Its axes are derived from those columns, so there is no second copy that can disagree", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='lens',
            name='coordinate_system',
            field=models.ForeignKey(blank=True, help_text="The coordinate system this lens' voxels are expressed in. An unsliced lens shares its dataset's; a sliced one has its own, with a stored edge carrying the shift", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lenses', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='meshcollection',
            name='coordinate_system',
            field=models.ForeignKey(blank=True, help_text="The coordinate system this collection's vertices are expressed in. An edge relates it to whatever the meshes were extracted from -- an identity when the grids agree, a scale when they do not", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mesh_collections', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='tabledataset',
            name='coordinate_system',
            field=models.ForeignKey(blank=True, help_text="The coordinate system this table's coordinate columns are expressed in. Its axes are derived from those columns, so there is no second copy that can disagree", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='table_datasets', to='core.coordinatesystem'),
        ),
        migrations.AlterField(
            model_name='coordinatesystem',
            name='annotation_collection',
            field=models.OneToOneField(blank=True, help_text='The annotation collection whose drawing space this is', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.annotationcollection'),
        ),
        migrations.AlterField(
            model_name='coordinatesystem',
            name='data_array',
            field=models.OneToOneField(blank=True, help_text='The pyramid level whose ARRAY (voxel index) space this is', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.dataarray'),
        ),
        migrations.AlterField(
            model_name='coordinatesystem',
            name='lens',
            field=models.OneToOneField(blank=True, help_text='The lens whose (cropped) space this is', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.lens'),
        ),
        migrations.AlterField(
            model_name='coordinatesystem',
            name='mesh_collection',
            field=models.OneToOneField(blank=True, help_text='The mesh collection whose vertex space this is', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.meshcollection'),
        ),
        migrations.AlterField(
            model_name='coordinatesystem',
            name='table_dataset',
            field=models.OneToOneField(blank=True, help_text='The table dataset whose row/coordinate space this is', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tabledataset'),
        ),
    ]
