# Generated by Django 6.0.6 on 2026-08-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayerstore',
            name='max_bytes',
            field=models.BigIntegerField(blank=True, help_text='The byte budget the upload grant advertised for this store, recorded so the advertised number and the delivered one can be compared. **Advertised, not enforced**: a session policy scopes what a credential may write, never how much, so S3 accepts an upload that exceeds this and `finish` accepts it as valid', null=True),
        ),
        migrations.AddField(
            model_name='datalayerstore',
            name='size_bytes',
            field=models.BigIntegerField(blank=True, help_text='How many bytes this store actually holds, measured when the upload was finished. Null while an upload is unfinished, or for stores written before this was recorded', null=True),
        ),
    ]
