# Generated by Django 6.0.6 on 2026-08-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayerstore',
            name='orphaned_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the last data row referencing this store was deleted, or null while it is still in use. A *candidate* for garbage collection, not an authority: `purge_orphaned_stores` re-checks for referrers before deleting anything, and clears this again if the store was re-attached in the meantime', null=True),
        ),
    ]
