# Generated by Django 6.0.6 on 2026-08-19 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datalayer", "0002_datalayerstore_max_bytes_datalayerstore_size_bytes"),
    ]

    operations = [
        migrations.CreateModel(
            name="SparseStore",
            fields=[
                (
                    "datalayerstore_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="datalayer.datalayerstore",
                    ),
                ),
                (
                    "encoding",
                    models.CharField(
                        blank=True,
                        help_text="The anndata encoding declared by the group: 'csr_matrix' or 'csc_matrix'. It says which axis `indptr` indexes, and so which question this store answers in one contiguous read",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "encoding_version",
                    models.CharField(
                        blank=True,
                        help_text="The version of that encoding, as the group declares it",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "shape",
                    models.JSONField(
                        blank=True,
                        help_text="The shape of the matrix, as the group declares it. Two axes",
                        null=True,
                    ),
                ),
                (
                    "nnz",
                    models.BigIntegerField(
                        blank=True,
                        help_text="How many nonzeros the matrix holds, read from the length of `data`",
                        null=True,
                    ),
                ),
                (
                    "dtype",
                    models.CharField(
                        blank=True,
                        help_text="The dtype of the stored values",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "chunks",
                    models.JSONField(
                        blank=True,
                        help_text="The chunk length of each of `data`, `indices` and `indptr`. Recorded because it is what decides the read cost: `indptr` names exactly which bytes a lookup wants, and a chunk is the granularity at which they can be fetched, so the two have to agree. Measured on a 16 um matrix, one slice costs 0.95 ms at 32 768-element chunks and 23.55 ms at 4 Mi ones -- the same bytes, a hundred times over-read",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("datalayer.datalayerstore",),
        ),
    ]
