# Generated by Django 6.0.6 on 2026-08-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayer', '0003_sparsestore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparsestore',
            name='chunks',
        ),
        migrations.RemoveField(
            model_name='sparsestore',
            name='dtype',
        ),
        migrations.RemoveField(
            model_name='sparsestore',
            name='encoding',
        ),
        migrations.RemoveField(
            model_name='sparsestore',
            name='encoding_version',
        ),
        migrations.RemoveField(
            model_name='sparsestore',
            name='nnz',
        ),
        migrations.AddField(
            model_name='sparsestore',
            name='layouts',
            field=models.JSONField(blank=True, help_text='The stored layouts, one entry per `layouts/<encoding>` child: its path, `encoding`, `encoding-version`, `nnz`, `dtype` and the chunk length of each of `data`, `indices` and `indptr`. Everything that differs between layouts, and nothing that does not. The chunking is here because it decides the read cost: `indptr` names exactly which bytes a lookup wants and a chunk is the granularity at which they can be fetched, so the two have to agree -- measured on a 16 um matrix, one slice costs 0.95 ms at 32 768-element chunks and 23.55 ms at 4 Mi ones, the same bytes a hundred times over-read', null=True),
        ),
        migrations.AddField(
            model_name='sparsestore',
            name='spec',
            field=models.CharField(blank=True, help_text='The version of the `mikro-sparse` block this store was accepted under. A spec selects how every byte in the prefix is read, so an unknown one is refused rather than guessed at', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='sparsestore',
            name='shape',
            field=models.JSONField(blank=True, help_text='The shape of the matrix, as the root block declares it and every layout agrees. Two axes', null=True),
        ),
    ]
