# Generated by Django 6.0.6 on 2026-08-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayer', '0004_remove_sparsestore_chunks_remove_sparsestore_dtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparsestore',
            name='spec',
            field=models.CharField(blank=True, help_text='The version of the `sporadik` block this store was accepted under. A spec selects how every byte in the prefix is read, so an unknown one is refused rather than guessed at', max_length=16, null=True),
        ),
    ]
