# Generated by Django 6.0.6 on 2026-08-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayer', '0005_alter_sparsestore_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='parquetstore',
            name='columns',
            field=models.JSONField(blank=True, help_text="The file's own schema, as DESCRIBE reports it: one entry per column with `name`, `type` and `nullable`, in file order. Read off the parquet when the upload was finished, never declared -- a fact derived from the artifact cannot be declared wrong, which is what a column's dtype used to be. Null only for a store written before this field existed, or one whose bytes could not be described.", null=True),
        ),
    ]
